In [1]:
import os
import re

import pandas as pd
pd.set_option('display.max_rows', None)

from astroquery.simbad import Simbad

observatiom_notes_dir = os.path.join(os.getcwd(), 'data')

print(observatiom_notes_dir)

/Users/jwatts/CelestialNav/git/StarGazerData/data

In [2]:
def extract_ngc_id(name):
    """
    Extract the NGC ID and friendly name from the given string.
    
    Parameters:
        name (str): The string from which to extract the NGC ID and friendly name.
        
    Returns:
        tuple: (ngc_id, friendly_name) where both are strings or None.
    """
    # Regex to extract NGC ID format, considering 'NGC ' followed by digits
    ngc_pattern = re.compile(r'(NGC \d+)(/[\d]+)?')
    ngc_match = ngc_pattern.search(name)
    
    # Extract NGC ID
    ngc_id = ngc_match.group(1) if ngc_match else None
    
    # Extract friendly name
    if ngc_id:
        friendly_name = name.replace(ngc_id, '').replace(ngc_match.group(2) if ngc_match.group(2) else '', '').strip() or None
    else:
        friendly_name = name.strip() or None
    
    return ngc_id, friendly_name

def get_friendly_name(ngc_id):
    friendly_name = None
    try:
        result_table = Simbad.query_objectids(ngc_id)
        if result_table is not None:
            names = [name[5:] for name in result_table['ID'] if name.startswith("NAME")]
            if names:
                friendly_name = max(names, key=len)

    except Exception as e:
        print(f"An error occurred while querying {ngc_id}: {str(e)}")
    return friendly_name

def convert_magnitude(value):
    try:
        return float(value)
    except (ValueError, TypeError):
        return pd.NA
    

def map_type(type_str):
    type_mapping = {
        'Star': 'star',
        'Open Cluster': 'cluster',
        'Globular Cluster': 'cluster',
        'Planetary Nebula': 'nebula',
        'Bright Nebula': 'nebula',
        'Diffuse Nebula': 'nebula',
        'Dark Nebula': 'nebula',
        'Supernova Remnant': 'nebula',
        'Spiral Galaxy': 'galaxy',
        'Elliptical Galaxy': 'galaxy',
        'Irregular Galaxy': 'galaxy',
        'Lenticular (S0) Galaxy': 'galaxy',
        'Star Cloud': 'star',
        'Double Star': 'star',
        'Group/Asterism': 'star'
    }
    return type_mapping.get(type_str, 'default')


def map_constellation(constellation_abbreviation):
    constellation_map = {
        'Cep': 'Cepheus', 'Dra': 'Draco', 'Cam': 'Camelopardalis', 'Cas': 'Cassiopeia',
        'Per': 'Perseus', 'Cyg': 'Cygnus', 'Lac': 'Lacerta', 'CVn': 'Canes Venatici',
        'And': 'Andromeda', 'Lyn': 'Lynx', 'Peg': 'Pegasus', 'Aur': 'Auriga',
        'Com': 'Coma Berenices', 'Vul': 'Vulpecula', 'Gem': 'Gemini', 'Leo': 'Leo',
        'Tau': 'Taurus', 'Del': 'Delphinus', 'Boo': 'Boötes', 'Mon': 'Monoceros',
        'Can': 'Canes Major', 'Cet': 'Cetus', 'Vir': 'Virgo', 'Sex': 'Sextans',
        'Aqr': 'Aquarius', 'Sgr': 'Sagittarius', 'CMa': 'Canis Major', 'Hya': 'Hydra',
        'Crv': 'Corvus', 'Scl': 'Sculptor', 'For': 'Fornax', 'CrA': 'Corona Australis',
        'Sco': 'Scorpius', 'Pup': 'Puppis', 'Col': 'Columba', 'Vel': 'Vela',
        'Cen': 'Centaurus', 'Ara': 'Ara', 'Hor': 'Horologium', 'Cir': 'Circinus',
        'Nor': 'Norma', 'Car': 'Carina', 'Pav': 'Pavo', 'Cru': 'Crux',
        'TrA': 'Triangulum Australe', 'Dor': 'Dorado', 'Tuc': 'Tucana', 'Mus': 'Musca',
        'Aps': 'Apus', 'Cha': 'Chamaeleon', 'Eri': 'Eridanus', 'Cnc': 'Cancer',
        'UMa': 'Ursa Major', 'Gru': 'Grus', 'Crt': 'Crater', 'Ori': 'Orion',
        'CrB': 'Corona Borealis', 'Psc': 'Pisces', 'Aql': 'Aquila', 'Ser': 'Serpens',
        'Phe': 'Phoenix', 'Lep': 'Lepus', 'Ari': 'Aries', 'Oph': 'Ophiuchus',
        'Her': 'Hercules', 'Cap': 'Capricornus', 'PsA': 'Piscis Austrinus',
        'CMi': 'Canis Minor', 'Equ': 'Equuleus', 'UMi': 'Ursa Minor', 'Tri': 'Triangulum',
        'Lib': 'Libra', 'Oct': 'Octans', 'LMi': 'Leo Minor', 'Sge': 'Sagitta', 'Lyr': 'Lyra'
    }
    
    return constellation_map.get(constellation_abbreviation, None)


def read_description_from_file(filename):
    full_path = os.path.join(observatiom_notes_dir, filename)

    try:
        with open(full_path, 'r', encoding='utf-8') as file:
            return file.read()
    except FileNotFoundError:
        return None

def extract_messier_objects(file):
    df = pd.read_csv(file)
    
    df['friendlyName'] = pd.NA
    
    df['ngcId'] = pd.NA
    df['catalogId'] = 'M' + df['ObjectNum'].astype(str)
    
    df['ra'] = pd.NA
    df['dec'] = pd.NA
    
    df['observationNotes'] = pd.NA
    
    # Iterate through the rows of the DataFrame
    for index, row in df.iterrows():
        ngc_id, friendly_name = extract_ngc_id(row['Name'])

        if (friendly_name == None):
            friendly_name = get_friendly_name(ngc_id)
            
        if (friendly_name == None):
            friendly_name = df.at[index, 'catalogId']
        
        df.at[index, 'friendlyName'] = friendly_name
        df.at[index, 'ngcId'] = ngc_id or pd.NA

        # RA and Dec collapse into coordinates column
        ra = (row['RAHour'] + row['RAMinute']/60) * 15
        df.at[index, 'ra'] = ra

        dec_sign = -1 if row['DecSign'].strip() == '-' else 1
        dec = dec_sign * (row['DecDeg'] + row['DecMinute']/60)
        df.at[index, 'dec'] = dec
        
        filename = f"m{row['ObjectNum']}.txt"
        observationNotes = read_description_from_file(filename)
        df.at[index, 'observationNotes'] = observationNotes or pd.NA

    df['Magnitude'] = df['Magnitude'].apply(convert_magnitude) 
    df['subType'] = df['Type']
    df['Type'] = df['Type'].apply(map_type)
        
    # Drop the original columns used to calculate RA and Dec
    df = df.drop(columns=['ObjectNum', 'Name', 'RAHour', 'RAMinute', 'DecSign', 'DecDeg', 'DecMinute', 'Info'])

    # Rename
    df.rename(columns={"Constellation": "constellation", "Magnitude": "magnitude", "Type": "type"}, inplace=True)

    
    # Reorder
    column_order = ['friendlyName', 'catalogId', 'ngcId', 'ra', 'dec', 'type', 'subType', 'constellation', 'magnitude', 'observationNotes']
    df = df[column_order]
    
    return df

def extract_caldwell_objects(file):
    df = pd.read_csv(file)
    
    df['friendlyName'] = pd.NA

    df['ngcId'] = pd.NA
    df['catalogId'] = 'Caldwell ' + df['ObjectNum'].astype(str)
    
    df['ra'] = pd.NA
    df['dec'] = pd.NA
    
    df['observationNotes'] = pd.NA

    # Iterate through the rows of the DataFrame
    for index, row in df.iterrows():
        ngc_id, friendly_name = extract_ngc_id(row['Name'])

        if (friendly_name == None):
            friendly_name = get_friendly_name(ngc_id)
        
        df.at[index, 'friendlyName'] = friendly_name or pd.NA
        df.at[index, 'ngcId'] = ngc_id or pd.NA

        if (friendly_name == None):
            friendly_name = ngc_id or df.at[index, 'catalogId']
        
        df.at[index, 'friendlyName'] = friendly_name
        df.at[index, 'ngcId'] = ngc_id or pd.NA

        # RA and Dec collapse into coordinates column
        ra = (row['RAHour'] + row['RAMinute']/60) * 15
        df.at[index, 'ra'] = ra

        dec_sign = -1 if row['DecSign'].strip() == '-' else 1
        dec = dec_sign * (row['DecDeg'] + row['DecMinute']/60)
        df.at[index, 'dec'] = dec  
    
        filename = f"caldwell{row['ObjectNum']}.txt"
        observationNotes = read_description_from_file(filename)
        df.at[index, 'observationNotes'] = observationNotes or pd.NA    
    
    df['Constellation'] = df['Constellation'].apply(map_constellation)
    df['Magnitude'] = df['Magnitude'].apply(convert_magnitude) 
    df['subType'] = df['Type']
    df['Type'] = df['Type'].apply(map_type)
    
    # Drop the original columns used to calculate RA and Dec
    df = df.drop(columns=['ObjectNum', 'Name', 'RAHour', 'RAMinute', 'DecSign', 'DecDeg', 'DecMinute', 'Info'])

    # Rename
    df.rename(columns={"Constellation": "constellation", "Magnitude": "magnitude", "Type": "type"}, inplace=True)
    
    # Reorder
    column_order = ['friendlyName', 'catalogId', 'ngcId', 'ra', 'dec', 'type', 'subType', 'constellation', 'magnitude', 'observationNotes']
    df = df[column_order]
    
    return df

def stars_convert_ra(ra_str):
    """Convert RA from hms format to decimal degrees."""
    # Extract hours, minutes, and seconds
    h, m, s = [float(i) for i in re.findall(r"\d+", ra_str)]
    # Convert to decimal degrees
    ra_deg = 15 * (h + m/60 + s/3600)
    return ra_deg

def stars_convert_dec(dec_str):
    """Convert Dec from °' format to decimal degrees."""
    # Handle the sign of the declination
    sign = -1 if "-" in dec_str else 1
    # Extract degrees and minutes
    deg, minute = [float(i) for i in re.findall(r"\d+", dec_str)]
    # Convert to decimal degrees
    dec_deg = sign * (deg + minute/60)
    return dec_deg

def extract_stars(file):
    df = pd.read_csv(file)
    
    df['ngcId'] = pd.NA
    df['catalogId'] = pd.NA
    
    df['type'] = 'star'
    df['subType'] = "star"
    df['ngcId'] = pd.NA
    
    df['Mag'] = df['Mag'].apply(convert_magnitude)
    df['Const'] = df['Const'].apply(map_constellation)
    
    df.rename(columns={"Name": "friendlyName", "RA": "ra", "Dec": "dec", "Const": "constellation", "Mag": "magnitude"}, inplace=True)

    df['ra'] = df['ra'].apply(stars_convert_ra)
    df['dec'] = df['dec'].apply(stars_convert_dec)

    df['observationNotes'] = pd.NA

    # Reorder
    column_order = ['friendlyName', 'catalogId', 'ngcId', 'ra', 'dec', 'type', 'subType', 'constellation', 'magnitude', 'observationNotes']
    df = df[column_order]
   
    return df

In [3]:
file = "MessierObjects.csv"
df_messier = extract_messier_objects(file)
df_messier[0:200]

,friendlyName,catalogId,ngcId,ra,dec,type,subType,constellation,magnitude,observationNotes
0,Crab Nebula,M1,NGC 1952,83.625,22.016667,nebula,Supernova Remnant,Taurus,8.4,"The Crab Nebula, or M1, is a supernova remnant..."
1,M2,M2,NGC 7089,323.375,-0.816667,cluster,Globular Cluster,Aquarius,6.5,<NA>
2,M3,M3,NGC 5272,205.55,28.383333,cluster,Globular Cluster,Canes Venatici,6.2,<NA>
3,M4,M4,NGC 6121,245.9,-26.533333,cluster,Globular Cluster,Scorpius,5.6,<NA>
4,M5,M5,NGC 5904,229.65,2.083333,cluster,Globular Cluster,Serpens Caput,5.6,<NA>
5,Butterfly Cluster,M6,NGC 6405,265.025,-32.216667,cluster,Open Cluster,Scorpius,5.3,"M6, also known as the Butterfly Cluster, is an..."
6,Ptolemy¹s Cluster,M7,NGC 6475,268.475,-34.816667,cluster,Open Cluster,Scorpius,4.1,"M7, known as the Ptolemy Cluster, is a promine..."
7,Lagoon Nebula,M8,NGC 6523,270.95,-24.383333,nebula,Diffuse Nebula,Sagittarius,6.0,"The Lagoon Nebula, or M8, is a large and brigh..."
8,M9,M9,NGC 6333,259.8,-18.516667,cluster,Globular Cluster,Ophiucus,7.7,<NA>
9,M10,M10,NGC 6254,254.275,-4.1,cluster,Globular Cluster,Ophiucus,6.6,<NA>
10,Wild Duck Cluster,M11,NGC 6705,282.775,-6.266667,cluster,Open Cluster,Scutum,6.3,"M11, or the Wild Duck Cluster, is an open clus..."
11,M12,M12,NGC 6218,251.8,-1.95,cluster,Globular Cluster,Ophiucus,6.7,<NA>
12,Hercules Globular Cluster,M13,NGC 6205,250.425,36.466667,cluster,Globular Cluster,Hercules,5.8,"M13, the Great Globular Cluster in Hercules, i..."
13,M14,M14,NGC 6402,264.4,-3.25,cluster,Globular Cluster,Ophiucus,7.6,<NA>
14,M15,M15,NGC 7078,322.5,12.166667,cluster,Globular Cluster,Pegasus,6.2,<NA>
15,Eagle Nebula Cluster,M16,NGC 6611,274.7,-13.783333,cluster,Open Cluster,Serpens Claudia,6.4,"The Eagle Nebula, or M16, is a young open clus..."
16,"Omega, Swan, Horseshoe Nebula",M17,NGC 6618,275.2,-16.183333,nebula,Diffuse Nebula,Sagittarius,7.0,"M17, also known as the Omega Nebula or the Swa..."
17,M18,M18,NGC 6613,274.975,-17.133333,cluster,Open Cluster,Sagittarius,7.5,<NA>
18,M19,M19,NGC 6273,255.65,-26.266667,cluster,Globular Cluster,Ophiucus,6.8,<NA>
19,Trifid Nebula,M20,NGC 6514,270.575,-23.033333,nebula,Diffuse Nebula,Sagittarius,9.0,<NA>
20,M21,M21,NGC 6531,271.15,-22.5,cluster,Open Cluster,Sagittarius,6.5,<NA>
21,M22,M22,NGC 6656,279.1,-23.9,cluster,Globular Cluster,Sagittarius,5.1,"M22, near the top of the 'teapot' in Sagittari..."
22,M23,M23,NGC 6494,269.2,-19.016667,cluster,Open Cluster,Sagittarius,6.9,<NA>
23,Milky Way Patch,M24,NGC 6603,274.6,-18.416667,star,Star Cloud,Sagittarius,4.6,<NA>
24,IC 4725,M25,<NA>,277.925,-19.233333,cluster,Open Cluster,Sagittarius,6.5,<NA>
25,M26,M26,NGC 6694,281.3,-9.4,cluster,Open Cluster,Scutum,8.0,<NA>
26,Dumbbell Nebula,M27,NGC 6853,299.9,22.716667,nebula,Planetary Nebula,Vulpecula,7.4,"M27, known as the Dumbbell Nebula, is a bright..."
27,M28,M28,NGC 6626,276.125,-24.866667,cluster,Globular Cluster,Sagittarius,6.8,<NA>
28,M29,M29,NGC 6913,305.975,38.533333,cluster,Open Cluster,Cygnus,7.1,<NA>
29,M30,M30,NGC 7099,325.1,-23.183333,cluster,Globular Cluster,Capricornus,7.2,<NA>
30,Andromeda Galaxy,M31,NGC 224,10.675,41.266667,galaxy,Spiral Galaxy,Andromeda,3.4,"The Andromeda Galaxy, known as M31, is one of ..."
31,Satellite of M31,M32,NGC 221,10.675,40.866667,galaxy,Elliptical Galaxy,Andromeda,8.1,<NA>
32,Triangulum/Pinwheel Galaxy,M33,NGC 598,23.475,30.65,galaxy,Spiral Galaxy,Triangulum,5.7,<NA>
33,M34,M34,NGC 1039,40.5,42.783333,cluster,Open Cluster,Perseus,5.5,<NA>
34,M35,M35,NGC 2168,92.225,24.333333,cluster,Open Cluster,Gemini,5.3,<NA>
35,M36,M36,NGC 1960,84.025,34.133333,cluster,Open Cluster,Auriga,6.3,<NA>
36,M37,M37,NGC 2099,88.1,32.55,cluster,Open Cluster,Auriga,6.2,<NA>
37,M38,M38,NGC 1912,82.175,35.833333,cluster,Open Cluster,Auriga,7.4,<NA>
38,M39,M39,NGC 7092,323.05,48.433333,cluster,Open Cluster,Cygnus,5.2,<NA>
39,Winecke 4,M40,<NA>,185.55,58.083333,star,Double Star,Ursa Major,<NA>,<NA>
40,M41,M41,NGC 2287,101.75,-20.733333,cluster,Open Cluster,Canis Major,4.6,<NA>
41,Great Orion Nebula,M42,NGC 1976,83.85,-5.45,nebula,Diffuse Nebula,Orion,4.0,"The Orion Nebula, or M42, is a diffuse nebula ..."
42,de Mairan¹s Nebula,M43,NGC 1982,83.9,-5.266667,nebula,Diffuse Nebula,Orion,9.0,<NA>
43,Beehive Cluster (Praesepe),M44,NGC 2632,130.025,19.983333,cluster,Open Cluster,Cancer,3.7,<NA>
44,"Pleiades, Subaru, Seven Sisters",M45,<NA>,56.75,24.12,cluster,Open Cluster,Taurus,1.6,"M45, commonly known as the Pleiades or the Sev..."
45,M46,M46,NGC 2437,115.45,-14.816667,cluster,Open Cluster,Puppis,6.0,<NA>
46,M47,M47,NGC 2422,114.15,-14.5,cluster,Open Cluster,Puppis,5.2,<NA>
47,M48,M48,NGC 2548,123.45,-5.8,cluster,Open Cluster,Hydra,5.5,<NA>
48,M49,M49,NGC 4472,187.45,8.0,galaxy,Elliptical Galaxy,Virgo,8.4,<NA>
49,M50,M50,NGC 2323,105.8,-8.333333,cluster,Open Cluster,Monocerus,6.3,<NA>
50,Whirlpool Galaxy,M51,NGC 5194,202.475,47.2,galaxy,Spiral Galaxy,Canes Venatici,8.4,"M51, also known as the Whirlpool Galaxy, is a ..."
51,M52,M52,NGC 7654,351.05,61.583333,cluster,Open Cluster,Cassiopeia,7.3,<NA>
52,M53,M53,NGC 5024,198.225,18.166667,cluster,Globular Cluster,Coma Berenices,7.6,<NA>
53,M54,M54,NGC 6715,283.775,-30.483333,cluster,Globular Cluster,Sagittarius,7.6,<NA>
54,M55,M55,NGC 6809,295.0,-30.966667,cluster,Globular Cluster,Sagittarius,6.3,<NA>
55,M56,M56,NGC 6779,289.15,30.183333,cluster,Globular Cluster,Lyra,8.3,<NA>
56,Ring Nebula,M57,NGC 6720,283.4,33.033333,nebula,Planetary Nebula,Lyra,8.8,"M57, the Ring Nebula, is a planetary nebula in..."
57,M58,M58,NGC 4579,189.425,11.816667,galaxy,Spiral Galaxy,Virgo,9.7,<NA>
58,M59,M59,NGC 4621,190.5,11.65,galaxy,Elliptical Galaxy,Virgo,9.6,<NA>
59,M60,M60,NGC 4649,190.925,11.55,galaxy,Elliptical Galaxy,Virgo,8.8,<NA>
60,M61,M61,NGC 4303,185.475,4.466667,galaxy,Spiral Galaxy,Virgo,9.7,<NA>
61,M62,M62,NGC 6266,255.3,-30.116667,cluster,Globular Cluster,Ophiucus,6.5,<NA>
62,Sunflower Galaxy,M63,NGC 5055,198.95,42.033333,galaxy,Spiral Galaxy,Canes Venatici,8.6,<NA>
63,Blackeye Galaxy,M64,NGC 4826,194.175,21.683333,galaxy,Spiral Galaxy,Coma Berenices,8.5,<NA>
64,M65,M65,NGC 3623,169.725,13.083333,galaxy,Spiral Galaxy,Leo,9.3,<NA>
65,M66,M66,NGC 3627,170.05,12.983333,galaxy,Spiral Galaxy,Leo,8.9,<NA>
66,M67,M67,NGC 2682,132.6,11.816667,cluster,Open Cluster,Cancer,6.1,<NA>
67,M68,M68,NGC 4590,189.875,-26.75,cluster,Globular Cluster,Hydra,7.8,<NA>
68,M69,M69,NGC 6637,277.85,-32.35,cluster,Globular Cluster,Sagittarius,7.6,<NA>
69,M70,M70,NGC 6681,280.8,-32.3,cluster,Globular Cluster,Sagittarius,7.9,<NA>
70,M71,M71,NGC 6838,298.45,18.783333,cluster,Globular Cluster,Sagitta,8.3,<NA>
71,M72,M72,NGC 6981,313.375,-12.533333,cluster,Globular Cluster,Aquarius,9.3,<NA>
72,Group of 4 stars,M73,NGC 6994,314.75,-12.633333,star,Group/Asterism,Aquarius,9.0,<NA>
73,M74,M74,NGC 628,24.175,15.783333,galaxy,Spiral Galaxy,Pisces,9.4,<NA>
74,M75,M75,NGC 6864,301.525,-21.916667,cluster,Globular Cluster,Sagittarius,8.5,<NA>
75,"Little Dumbell, Cork, Butterfly Nebula",M76,NGC 650,25.575,51.566667,nebula,Planetary Nebula,Perseus,10.1,<NA>
76,Cetus A,M77,NGC 1068,40.675,0.016667,galaxy,Spiral Galaxy,Cetus,8.9,<NA>
77,M78,M78,NGC 2068,86.675,0.05,nebula,Diffuse Nebula,Orion,8.3,<NA>
78,M79,M79,NGC 1904,81.125,-24.55,cluster,Globular Cluster,Lepus,7.7,<NA>
79,M80,M80,NGC 6093,244.25,-22.983333,cluster,Globular Cluster,Scorpius,7.3,<NA>
80,Bode¹s Galaxy,M81,NGC 3031,148.9,69.066667,galaxy,Spiral Galaxy,Ursa Major,6.9,"M81, or Bode's Galaxy, is a grand design spira..."
81,Cigar Galaxy,M82,NGC 3034,148.95,69.683333,galaxy,Irregular Galaxy,Ursa Major,8.4,"M82, the Cigar Galaxy, is a starburst galaxy n..."
82,Southern Pinwheel Galaxy,M83,NGC 5236,204.25,-29.866667,galaxy,Spiral Galaxy,Hydra,7.6,<NA>
83,M84,M84,NGC 4374,186.275,12.883333,galaxy,Lenticular (S0) Galaxy,Virgo,9.1,<NA>
84,M85,M85,NGC 4382,186.35,18.183333,galaxy,Lenticular (S0) Galaxy,Coma Berenices,9.1,<NA>
85,FAUST V051,M86,NGC 4406,186.55,12.95,galaxy,Lenticular (S0) Galaxy,Virgo,8.9,<NA>
86,Virgo A,M87,NGC 4486,187.7,12.4,galaxy,Elliptical Galaxy,Virgo,8.6,<NA>
87,M88,M88,NGC 4501,188.0,14.416667,galaxy,Spiral Galaxy,Coma Berenices,9.6,<NA>
88,M89,M89,NGC 4552,188.925,12.55,galaxy,Elliptical Galaxy,Virgo,9.8,<NA>
89,M90,M90,NGC 4569,189.2,13.166667,galaxy,Spiral Galaxy,Virgo,9.5,<NA>
90,M91,M91,NGC 4548,188.85,14.5,galaxy,Spiral Galaxy,Coma Berenices,10.2,<NA>
91,M92,M92,NGC 6341,259.275,43.133333,cluster,Globular Cluster,Hercules,6.4,<NA>
92,M93,M93,NGC 2447,116.15,-23.866667,cluster,Open Cluster,Puppis,6.0,<NA>
93,M94,M94,NGC 4736,192.725,41.116667,galaxy,Spiral Galaxy,Canes Venatici,8.2,<NA>
94,M95,M95,NGC 3351,161.0,11.7,galaxy,Spiral Galaxy,Leo,9.7,<NA>
95,M96,M96,NGC 3368,161.7,11.816667,galaxy,Spiral Galaxy,Leo,9.2,<NA>
96,Owl Nebula,M97,NGC 3587,168.7,55.016667,nebula,Planetary Nebula,Ursa Major,9.9,<NA>
97,M98,M98,NGC 4192,183.45,14.9,galaxy,Spiral Galaxy,Coma Berenices,10.1,<NA>
98,Virgo Cluster Pinwheel,M99,NGC 4254,184.7,14.416667,galaxy,Spiral Galaxy,Coma Berenices,9.9,<NA>
99,M100,M100,NGC 4321,185.725,15.816667,galaxy,Spiral Galaxy,Coma Berenices,9.3,<NA>
100,Pinwheel Galaxy,M101,NGC 5457,210.8,54.35,galaxy,Spiral Galaxy,Ursa Major,7.9,<NA>
101,Spindle Galaxy,M102,NGC 5866,226.625,55.766667,galaxy,Lenticular (S0) Galaxy,Draco,9.9,<NA>
102,M103,M103,NGC 581,23.3,60.7,cluster,Open Cluster,Cassiopeia,7.4,<NA>
103,Sombrero Galaxy,M104,NGC 4594,190.0,-11.616667,galaxy,Spiral Galaxy,Virgo,8.0,<NA>
104,M105,M105,NGC 3379,161.95,12.583333,galaxy,Elliptical Galaxy,Leo,9.3,<NA>
105,M106,M106,NGC 4258,184.75,47.3,galaxy,Spiral Galaxy,Canes Venatici,8.4,<NA>
106,M107,M107,NGC 6171,248.125,-13.05,cluster,Globular Cluster,Ophiucus,7.9,<NA>
107,M108,M108,NGC 3556,167.875,55.666667,galaxy,Spiral Galaxy,Ursa Major,10.0,<NA>
108,M109,M109,NGC 3992,179.4,53.383333,galaxy,Spiral Galaxy,Ursa Major,9.8,<NA>
109,Satellite of M31,M110,NGC 205,10.1,41.683333,galaxy,Elliptical Galaxy,Andromeda,8.5,<NA>

In [4]:
file = "CaldwellObjects.csv"
df_caldwell = extract_caldwell_objects(file)


# Provide some friendly names not provided by Simbad
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 2", "friendlyName"] = "Bow-Tie Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 5", "friendlyName"] = "Hidden Galaxy"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 6", "friendlyName"] = "Cat's Eye Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 9", "friendlyName"] = "Cave Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 12", "friendlyName"] = "Fireworks Galaxy"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 14", "friendlyName"] = "Double Cluster (h&X Persei)"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 19", "friendlyName"] = "Cocoon Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 23", "friendlyName"] = "Silver Sliver Galaxy"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 31", "friendlyName"] = "Flaming Star Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 33", "friendlyName"] = "East Veil"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 34", "friendlyName"] = "West Veil"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 35", "friendlyName"] = "Coma B"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 38", "friendlyName"] = "Needle Galaxy"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 39", "friendlyName"] = "Eskimo/Clown Face Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 41", "friendlyName"] = "Hyades Cluster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 46", "friendlyName"] = "Hubble's Variable Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 49", "friendlyName"] = "Rosette Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 50", "friendlyName"] = "Satellite Cluster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 56", "friendlyName"] = "Skull Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 60", "friendlyName"] = "Antennae Galaxies"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 61", "friendlyName"] = "Antennae Galaxies" # same as C60
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 68", "friendlyName"] = "R CrA Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 80", "friendlyName"] = "Omega Centauri"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 85", "friendlyName"] = "Omicron Velorum Cluster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 89", "friendlyName"] = "S Normae Cluster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 91", "friendlyName"] = "Wishing Well Culster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 92", "friendlyName"] = "Eta Carinae Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 93", "friendlyName"] = "Great Peacock Globular"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 96", "friendlyName"] = "Southern Beehive Cluster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 97", "friendlyName"] = "Pearl Cluster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 99", "friendlyName"] = "Coalsack Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 100", "friendlyName"] = "Lambda Centauri Nebula"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 102", "friendlyName"] = "Theta Car Cluster"
df_caldwell.loc[df_caldwell['catalogId'] == "Caldwell 103", "friendlyName"] = "Tarantula Nebula"

#df_caldwell[['catalogId', 'friendlyName', 'desc']]

df_caldwell[0:200]

,friendlyName,catalogId,ngcId,ra,dec,type,subType,constellation,magnitude,observationNotes
0,NGC 188,Caldwell 1,NGC 188,11.1,85.333333,cluster,Open Cluster,Cepheus,8.1,caldwell 1 data
1,Bow-Tie Nebula,Caldwell 2,NGC 40,3.25,72.533333,nebula,Planetary Nebula,Cepheus,12.4,<NA>
2,NGC 4236,Caldwell 3,NGC 4236,184.175,69.466667,galaxy,Spiral Galaxy,Draco,9.7,<NA>
3,IRIS Nebula,Caldwell 4,NGC 7023,315.45,68.2,nebula,Bright Nebula,Cepheus,<NA>,<NA>
4,Hidden Galaxy,Caldwell 5,<NA>,56.7,68.1,galaxy,Spiral Galaxy,Camelopardalis,9.2,<NA>
5,Cat's Eye Nebula,Caldwell 6,NGC 6543,269.65,66.633333,nebula,Planetary Nebula,Draco,8.1,<NA>
6,NGC 2403,Caldwell 7,NGC 2403,114.225,65.6,galaxy,Spiral Galaxy,Camelopardalis,8.4,<NA>
7,NGC 559,Caldwell 8,NGC 559,22.375,63.3,cluster,Open Cluster,Cassiopeia,9.5,<NA>
8,Cave Nebula,Caldwell 9,<NA>,344.2,62.616667,nebula,Bright Nebula,Cepheus,<NA>,<NA>
9,NGC 663,Caldwell 10,NGC 663,26.5,61.25,cluster,Open Cluster,Cassiopeia,7.1,<NA>
10,Bubble Nebula,Caldwell 11,NGC 7635,350.175,61.2,nebula,Bright Nebula,Cassiopeia,<NA>,<NA>
11,Fireworks Galaxy,Caldwell 12,NGC 6946,308.7,60.15,galaxy,Spiral Galaxy,Cepheus,8.9,<NA>
12,Owl Cluster,Caldwell 13,NGC 457,19.775,58.333333,cluster,Open Cluster,Cassiopeia,6.4,<NA>
13,Double Cluster (h&X Persei),Caldwell 14,NGC 869,35.0,57.133333,cluster,Open Cluster,Perseus,4.3,"Caldwell 14, also known as the Double Cluster,..."
14,Blinking Planetary,Caldwell 15,NGC 6826,296.2,50.516667,nebula,Planetary Nebula,Cygnus,8.8,<NA>
15,NGC 7243,Caldwell 16,NGC 7243,333.825,49.883333,cluster,Open Cluster,Lacerta,6.4,<NA>
16,NGC 147,Caldwell 17,NGC 147,8.3,48.5,galaxy,Elliptical Galaxy,Cassiopeia,9.3,<NA>
17,NGC 185,Caldwell 18,NGC 185,9.75,48.333333,galaxy,Elliptical Galaxy,Cassiopeia,9.2,<NA>
18,Cocoon Nebula,Caldwell 19,<NA>,328.375,47.266667,nebula,Bright Nebula,Cygnus,<NA>,<NA>
19,North America Nebula,Caldwell 20,NGC 7000,314.7,44.333333,nebula,Bright Nebula,Cygnus,<NA>,<NA>
20,NGC 4449,Caldwell 21,NGC 4449,187.05,44.1,galaxy,Irregular Galaxy,Canes Venatici,9.4,<NA>
21,Copeland's Blue Snowball,Caldwell 22,NGC 7662,351.475,42.55,nebula,Planetary Nebula,Andromeda,8.3,<NA>
22,Silver Sliver Galaxy,Caldwell 23,NGC 891,35.65,42.35,galaxy,Spiral Galaxy,Andromeda,9.9,<NA>
23,Perseus A,Caldwell 24,NGC 1275,49.95,41.516667,galaxy,Irregular Galaxy,Perseus,11.6,<NA>
24,NGC 2419,Caldwell 25,NGC 2419,114.525,38.883333,cluster,Globular Cluster,Lynx,10.4,<NA>
25,NGC 4244,Caldwell 26,NGC 4244,184.375,37.816667,galaxy,Spiral Galaxy,Canes Venatici,10.2,<NA>
26,Crescent Nebula,Caldwell 27,NGC 6888,303.0,38.35,nebula,Bright Nebula,Cygnus,<NA>,<NA>
27,NGC 752,Caldwell 28,NGC 752,29.45,37.683333,cluster,Open Cluster,Andromeda,5.7,<NA>
28,NGC 5005,Caldwell 29,NGC 5005,197.725,37.05,galaxy,Spiral Galaxy,Canes Venatici,9.8,<NA>
29,NGC 7331,Caldwell 30,NGC 7331,339.275,34.416667,galaxy,Spiral Galaxy,Pegasus,9.5,<NA>
30,Flaming Star Nebula,Caldwell 31,<NA>,79.05,34.266667,nebula,Bright Nebula,Auriga,<NA>,<NA>
31,Whale Galaxy,Caldwell 32,NGC 4631,190.525,32.533333,galaxy,Spiral Galaxy,Canes Venatici,9.3,<NA>
32,East Veil,Caldwell 33,NGC 6992,314.1,31.716667,nebula,Supernova Remnant,Cygnus,<NA>,"Caldwell 33, located in Draco, is a spiral gal..."
33,West Veil,Caldwell 34,NGC 6960,311.425,30.716667,nebula,Supernova Remnant,Cygnus,<NA>,"Caldwell 34, part of the Veil Nebula, is a sup..."
34,Coma B,Caldwell 35,NGC 4889,195.025,27.983333,galaxy,Elliptical Galaxy,Coma Berenices,11.4,<NA>
35,NGC 4559,Caldwell 36,NGC 4559,189.0,27.966667,galaxy,Spiral Galaxy,Coma Berenices,9.8,<NA>
36,NGC 6885,Caldwell 37,NGC 6885,303.0,26.483333,cluster,Open Cluster,Vulpecula,5.9,<NA>
37,Needle Galaxy,Caldwell 38,NGC 4565,189.075,25.983333,galaxy,Spiral Galaxy,Coma Berenices,9.6,<NA>
38,Eskimo/Clown Face Nebula,Caldwell 39,NGC 2392,112.3,20.916667,nebula,Planetary Nebula,Gemini,9.2,<NA>
39,NGC 3626,Caldwell 40,NGC 3626,170.025,18.35,galaxy,Spiral Galaxy,Leo,10.9,<NA>
40,Hyades Cluster,Caldwell 41,<NA>,66.75,16.0,cluster,Open Cluster,Taurus,0.5,<NA>
41,NGC 7006,Caldwell 42,NGC 7006,315.375,16.183333,cluster,Globular Cluster,Delphinus,10.6,<NA>
42,NGC 7814,Caldwell 43,NGC 7814,0.825,16.15,galaxy,Spiral Galaxy,Pegasus,10.5,<NA>
43,NGC 7479,Caldwell 44,NGC 7479,346.225,12.316667,galaxy,Spiral Galaxy,Pegasus,11.0,<NA>
44,NGC 5248,Caldwell 45,NGC 5248,204.375,8.883333,galaxy,Spiral Galaxy,Boötes,10.2,<NA>
45,Hubble's Variable Nebula,Caldwell 46,NGC 2261,99.8,8.733333,nebula,Bright Nebula,Monoceros,<NA>,<NA>
46,NGC 6934,Caldwell 47,NGC 6934,308.55,7.4,cluster,Globular Cluster,Delphinus,8.9,<NA>
47,NGC 2775,Caldwell 48,NGC 2775,137.575,7.033333,galaxy,Spiral Galaxy,Canes Major,10.3,<NA>
48,Rosette Nebula,Caldwell 49,NGC 2237,98.075,5.05,nebula,Bright Nebula,Monoceros,<NA>,"Caldwell 49, known as the Rosette Nebula, is a..."
49,Satellite Cluster,Caldwell 50,NGC 2244,98.1,4.866667,cluster,Open Cluster,Monoceros,4.8,<NA>
50,IC 1613,Caldwell 51,<NA>,16.2,2.116667,galaxy,Irregular Galaxy,Cetus,9.3,<NA>
51,NGC 4697,Caldwell 52,NGC 4697,192.15,-5.8,galaxy,Elliptical Galaxy,Virgo,9.3,<NA>
52,Spindle Galaxy,Caldwell 53,NGC 3115,151.3,-7.716667,galaxy,Elliptical Galaxy,Sextans,9.1,<NA>
53,NGC 2506,Caldwell 54,NGC 2506,120.05,-10.783333,cluster,Open Cluster,Monoceros,7.6,<NA>
54,Saturn Nebula,Caldwell 55,NGC 7009,316.05,-11.366667,nebula,Planetary Nebula,Aquarius,8.0,<NA>
55,Skull Nebula,Caldwell 56,NGC 246,11.75,-11.883333,nebula,Planetary Nebula,Cetus,10.9,<NA>
56,Barnard's Galaxy,Caldwell 57,NGC 6822,296.225,-14.8,galaxy,Irregular Galaxy,Sagittarius,8.8,<NA>
57,Caroline's Cluster,Caldwell 58,NGC 2360,109.45,-15.616667,cluster,Open Cluster,Canis Major,7.2,<NA>
58,Jupiter's Ghost Nebula,Caldwell 59,NGC 3242,156.2,-18.633333,nebula,Planetary Nebula,Hydra,7.8,<NA>
59,Antennae Galaxies,Caldwell 60,NGC 4038,180.475,-18.866667,galaxy,Spiral Galaxy,Corvus,10.7,<NA>
60,Antennae Galaxies,Caldwell 61,NGC 4039,180.475,-18.883333,galaxy,Spiral Galaxy,Corvus,10.7,<NA>
61,NGC 247,Caldwell 62,NGC 247,11.775,-20.766667,galaxy,Spiral Galaxy,Cetus,9.1,<NA>
62,Helix Nebula,Caldwell 63,NGC 7293,337.4,-20.8,nebula,Planetary Nebula,Aquarius,7.3,<NA>
63,Tau CMa,Caldwell 64,NGC 2362,109.7,-24.95,cluster,Open Cluster,Canis Major,4.1,"Caldwell 64, the Black Eye Galaxy or M64, is a..."
64,Sculptor Filament,Caldwell 65,NGC 253,11.9,-25.283333,galaxy,Spiral Galaxy,Sculptor,7.1,<NA>
65,NGC 5694,Caldwell 66,NGC 5694,219.9,-26.533333,cluster,Globular Cluster,Hydra,10.2,<NA>
66,NGC 1097,Caldwell 67,NGC 1097,41.575,-30.283333,galaxy,Spiral Galaxy,Fornax,9.2,<NA>
67,R CrA Nebula,Caldwell 68,NGC 6729,285.475,-36.95,nebula,Bright Nebula,Corona Australis,<NA>,<NA>
68,Bug Nebula,Caldwell 69,NGC 6302,258.425,-37.1,nebula,Planetary Nebula,Scorpius,9.6,<NA>
69,NGC 300,Caldwell 70,NGC 300,13.725,-37.683333,galaxy,Spiral Galaxy,Sculptor,8.7,<NA>
70,NGC 2477,Caldwell 71,NGC 2477,118.075,-38.55,cluster,Open Cluster,Puppis,5.8,<NA>
71,NGC 55,Caldwell 72,NGC 55,3.725,-39.183333,galaxy,Spiral Galaxy,Sculptor,7.9,<NA>
72,NGC 1851,Caldwell 73,NGC 1851,78.525,-40.05,cluster,Globular Cluster,Columba,7.3,<NA>
73,Eight-Burst Nebula,Caldwell 74,NGC 3132,151.925,-40.433333,nebula,Planetary Nebula,Vela,9.4,<NA>
74,NGC 6124,Caldwell 75,NGC 6124,246.4,-40.666667,cluster,Open Cluster,Scorpius,5.8,<NA>
75,NGC 6231,Caldwell 76,NGC 6231,253.5,-41.8,cluster,Open Cluster,Scorpius,2.6,<NA>
76,Centaurus A,Caldwell 77,NGC 5128,201.375,-43.016667,galaxy,Elliptical Galaxy,Centaurus,7.0,<NA>
77,NGC 6541,Caldwell 78,NGC 6541,272.0,-43.7,cluster,Globular Cluster,Corona Australis,6.6,<NA>
78,NGC 3201,Caldwell 79,NGC 3201,154.4,-46.416667,cluster,Globular Cluster,Vela,6.7,<NA>
79,Omega Centauri,Caldwell 80,NGC 5139,201.7,-47.483333,cluster,Globular Cluster,Centaurus,3.6,<NA>
80,NGC 6352,Caldwell 81,NGC 6352,261.375,-48.416667,cluster,Globular Cluster,Ara,8.1,<NA>
81,NGC 6193,Caldwell 82,NGC 6193,250.325,-48.766667,cluster,Open Cluster,Ara,5.2,<NA>
82,NGC 4945,Caldwell 83,NGC 4945,196.35,-49.466667,galaxy,Spiral Galaxy,Centaurus,8.7,<NA>
83,NGC 5286,Caldwell 84,NGC 5286,206.6,-51.366667,cluster,Globular Cluster,Centaurus,7.6,<NA>
84,Omicron Velorum Cluster,Caldwell 85,<NA>,130.05,-53.066667,cluster,Open Cluster,Vela,2.5,<NA>
85,NGC 6397,Caldwell 86,NGC 6397,265.175,-53.666667,cluster,Globular Cluster,Ara,5.6,<NA>
86,NGC 1261,Caldwell 87,NGC 1261,48.075,-55.216667,cluster,Globular Cluster,Horologium,8.4,<NA>
87,NGC 5823,Caldwell 88,NGC 5823,226.425,-55.6,cluster,Open Cluster,Circinus,7.9,<NA>
88,S Normae Cluster,Caldwell 89,NGC 6087,244.725,-57.9,cluster,Open Cluster,Norma,5.4,<NA>
89,NGC 2867,Caldwell 90,NGC 2867,140.35,-58.316667,nebula,Planetary Nebula,Carina,<NA>,<NA>
90,Wishing Well Culster,Caldwell 91,NGC 3532,166.6,-58.666667,cluster,Open Cluster,Carina,3.0,<NA>
91,Eta Carinae Nebula,Caldwell 92,NGC 3372,160.95,-59.866667,nebula,Bright Nebula,Carina,<NA>,<NA>
92,Great Peacock Globular,Caldwell 93,NGC 6752,287.725,-59.983333,cluster,Globular Cluster,Pavo,5.4,<NA>
93,Herschel's Jewel Box,Caldwell 94,NGC 4755,193.4,-60.333333,cluster,Open Cluster,Crux,4.2,<NA>
94,NGC 6025,Caldwell 95,NGC 6025,240.925,-60.5,cluster,Open Cluster,Triangulum Australe,5.1,<NA>
95,Southern Beehive Cluster,Caldwell 96,NGC 2516,119.575,-60.866667,cluster,Open Cluster,Carina,3.8,<NA>
96,Pearl Cluster,Caldwell 97,NGC 3766,174.025,-61.616667,cluster,Open Cluster,Centaurus,5.3,<NA>
97,Coalsack Cluster,Caldwell 98,NGC 4609,190.575,-62.966667,cluster,Open Cluster,Crux,6.9,<NA>
98,Coalsack Nebula,Caldwell 99,<NA>,193.25,-63.0,nebula,Dark Nebula,Crux,<NA>,<NA>
99,Lambda Centauri Nebula,Caldwell 100,<NA>,174.15,-63.033333,cluster,Open Cluster,Centaurus,4.5,<NA>
100,NGC 6744,Caldwell 101,NGC 6744,287.45,-63.85,galaxy,Spiral Galaxy,Pavo,8.3,<NA>
101,Theta Car Cluster,Caldwell 102,<NA>,160.8,-64.4,cluster,Open Cluster,Carina,1.9,<NA>
102,Tarantula Nebula,Caldwell 103,NGC 2070,84.675,-69.1,nebula,Bright Nebula,Dorado,<NA>,<NA>
103,NGC 362,Caldwell 104,NGC 362,15.8,-70.85,cluster,Globular Cluster,Tucana,6.6,"Caldwell 104, also known as the Sombrero Galax..."
104,NGC 4833,Caldwell 105,NGC 4833,194.9,-70.883333,cluster,Globular Cluster,Musca,7.3,<NA>
105,47 Tuc Cluster,Caldwell 106,NGC 104,6.025,-72.083333,cluster,Globular Cluster,Tucana,4.0,<NA>
106,NGC 6101,Caldwell 107,NGC 6101,246.45,-72.2,cluster,Globular Cluster,Apus,9.3,<NA>
107,NGC 4372,Caldwell 108,NGC 4372,186.45,-72.666667,cluster,Globular Cluster,Musca,7.8,<NA>
108,NGC 3195,Caldwell 109,NGC 3195,152.375,-80.866667,nebula,Planetary Nebula,Chamaeleon,<NA>,<NA>

In [5]:
file = "Alignment Stars.csv"
df_stars = extract_stars(file)
df_stars[0:5]

,friendlyName,catalogId,ngcId,ra,dec,type,subType,constellation,magnitude,observationNotes
0,Acamar,<NA>,<NA>,44.566667,-40.300000,star,star,Eridanus,3.2,<NA>
1,Achernar,<NA>,<NA>,24.429167,-57.233333,star,star,Eridanus,0.5,<NA>
2,Achird,<NA>,<NA>,12.275000,57.816667,star,star,Cassiopeia,3.4,<NA>
3,Acrux,<NA>,<NA>,186.650000,-63.100000,star,star,Crux,1.3,<NA>
4,Acubens,<NA>,<NA>,134.620833,11.850000,star,star,Cancer,4.3,<NA>

In [6]:
df_combined = pd.concat([df_messier, df_caldwell, df_stars], ignore_index=True)

df_combined['id'] = 0
df_combined['observationStatus'] = 'NOT_OBSERVED'

In [7]:
df_combined['type'].value_counts()

star       250
cluster    102
galaxy      75
nebula      39
Name: type, dtype: int64

In [8]:
# Set the observation status of a few well known goods
df_combined.loc[df_combined['catalogId'] == "M1", 'observationStatus'] = 'SUGGESTED'  # Crab Nebula
df_combined.loc[df_combined['catalogId'] == "M6", 'observationStatus'] = 'GREAT'  # Butterfly Cluster
df_combined.loc[df_combined['catalogId'] == "M7", 'observationStatus'] = 'GREAT'  # Ptolemy's Cluster
df_combined.loc[df_combined['catalogId'] == "M8", 'observationStatus'] = 'GREAT'  # Lagoon Nebula
df_combined.loc[df_combined['catalogId'] == "M11", 'observationStatus'] = 'GREAT'  # Wild Duck Cluster
df_combined.loc[df_combined['catalogId'] == "M13", 'observationStatus'] = 'GREAT'  # Hercules Globular Cluster
df_combined.loc[df_combined['catalogId'] == "M16", 'observationStatus'] = 'SUGGESTED'  # Eagle Nebula
df_combined.loc[df_combined['catalogId'] == "M17", 'observationStatus'] = 'SUGGESTED'  # The Omega or Swan Nebula
df_combined.loc[df_combined['catalogId'] == "M22", 'observationStatus'] = 'SUGGESTED'  # Sagittarius cluster
df_combined.loc[df_combined['catalogId'] == "M27", 'observationStatus'] = 'GREAT'  # Dumbell nebula
df_combined.loc[df_combined['catalogId'] == "M31", 'observationStatus'] = 'GREAT'  # Andromeda Galaxy
df_combined.loc[df_combined['catalogId'] == "M42", 'observationStatus'] = 'GREAT'  # Orion Nebula
df_combined.loc[df_combined['catalogId'] == "M45", 'observationStatus'] = 'GREAT'  # Pleaiades
df_combined.loc[df_combined['catalogId'] == "M51", 'observationStatus'] = 'SUGGESTED'  # Whirlpool Galaxy
df_combined.loc[df_combined['catalogId'] == "M57", 'observationStatus'] = 'SUGGESTED'  # The Ring Nebula
df_combined.loc[df_combined['catalogId'] == "M81", 'observationStatus'] = 'SUGGESTED'  # The Bode's Galaxy
df_combined.loc[df_combined['catalogId'] == "M82", 'observationStatus'] = 'SUGGESTED'  # The Cigar Galaxy
df_combined.loc[df_combined['catalogId'] == "Caldwell 14", 'observationStatus'] = 'GREAT'  # Double Cluster
df_combined.loc[df_combined['catalogId'] == "Caldwell 33", 'observationStatus'] = 'SUGGESTED'  # Eastern Veil
df_combined.loc[df_combined['catalogId'] == "Caldwell 34", 'observationStatus'] = 'SUGGESTED'  # Western Veil 
df_combined.loc[df_combined['catalogId'] == "Caldwell 49", 'observationStatus'] = 'SUGGESTED'  # Rosette Nebula
df_combined.loc[df_combined['catalogId'] == "Caldwell 64", 'observationStatus'] = 'SUGGESTED'  # Cat's Eye Nebula
df_combined.loc[df_combined['catalogId'] == "Caldwell 104", 'observationStatus'] = 'SUGGESTED'  # Sombrero Galaxy

In [9]:
df_combined.head()

,friendlyName,catalogId,ngcId,ra,dec,type,subType,constellation,magnitude,observationNotes,id,observationStatus
0,Crab Nebula,M1,NGC 1952,83.625,22.016667,nebula,Supernova Remnant,Taurus,8.4,"The Crab Nebula, or M1, is a supernova remnant...",0,SUGGESTED
1,M2,M2,NGC 7089,323.375,-0.816667,cluster,Globular Cluster,Aquarius,6.5,<NA>,0,NOT_OBSERVED
2,M3,M3,NGC 5272,205.55,28.383333,cluster,Globular Cluster,Canes Venatici,6.2,<NA>,0,NOT_OBSERVED
3,M4,M4,NGC 6121,245.9,-26.533333,cluster,Globular Cluster,Scorpius,5.6,<NA>,0,NOT_OBSERVED
4,M5,M5,NGC 5904,229.65,2.083333,cluster,Globular Cluster,Serpens Caput,5.6,<NA>,0,NOT_OBSERVED

In [10]:
df_combined.to_json('items.json', orient='records', lines=False)