In [1]:
import os
import re

import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.float_format', '{:.6f}'.format)

from astroquery.simbad import Simbad

observatiom_notes_dir = os.path.join(os.getcwd(), 'data')
print(observatiom_notes_dir)

/Users/jwatts/CelestialNav/git/StarGazerData/data

In [2]:
def extract_ngc_id(name):
    """
    Extract the NGC ID and friendly name from the given string.
    
    Parameters:
        name (str): The string from which to extract the NGC ID and friendly name.
        
    Returns:
        tuple: (ngc_id, friendly_name) where both are strings or None.
    """
    # Regex to extract NGC ID format, considering 'NGC ' followed by digits
    ngc_pattern = re.compile(r'(NGC \d+)(/[\d]+)?')
    ngc_match = ngc_pattern.search(name)
    
    # Extract NGC ID
    ngc_id = ngc_match.group(1) if ngc_match else None
    
    # Extract friendly name
    if ngc_id:
        friendly_name = name.replace(ngc_id, '').replace(ngc_match.group(2) if ngc_match.group(2) else '', '').strip() or None
    else:
        friendly_name = name.strip() or None
    
    return ngc_id, friendly_name

def get_friendly_name(ngc_id):
    friendly_name = None
    try:
        result_table = Simbad.query_objectids(ngc_id)
        if result_table is not None:
            names = [name[5:] for name in result_table['ID'] if name.startswith("NAME")]
            if names:
                friendly_name = max(names, key=len)

    except Exception as e:
        print(f"An error occurred while querying {ngc_id}: {str(e)}")
    return friendly_name

def convert_magnitude(value):
    try:
        return float(value)
    except (ValueError, TypeError):
        return pd.NA
    

def map_type(type_str):
    type_mapping = {
        'Star': 'star',
        'Open Cluster': 'cluster',
        'Globular Cluster': 'cluster',
        'Planetary Nebula': 'nebula',
        'Bright Nebula': 'nebula',
        'Diffuse Nebula': 'nebula',
        'Dark Nebula': 'nebula',
        'Supernova Remnant': 'nebula',
        'Spiral Galaxy': 'galaxy',
        'Elliptical Galaxy': 'galaxy',
        'Irregular Galaxy': 'galaxy',
        'Lenticular (S0) Galaxy': 'galaxy',
        'Star Cloud': 'star',
        'Double Star': 'star',
        'Group/Asterism': 'star'
    }
    return type_mapping.get(type_str, 'default')


def map_constellation(constellation_abbreviation):
    constellation_map = {
        'Cep': 'Cepheus', 'Dra': 'Draco', 'Cam': 'Camelopardalis', 'Cas': 'Cassiopeia',
        'Per': 'Perseus', 'Cyg': 'Cygnus', 'Lac': 'Lacerta', 'CVn': 'Canes Venatici',
        'And': 'Andromeda', 'Lyn': 'Lynx', 'Peg': 'Pegasus', 'Aur': 'Auriga',
        'Com': 'Coma Berenices', 'Vul': 'Vulpecula', 'Gem': 'Gemini', 'Leo': 'Leo',
        'Tau': 'Taurus', 'Del': 'Delphinus', 'Boo': 'Bootes', 'Mon': 'Monoceros',
        'Can': 'Canes Major', 'Cet': 'Cetus', 'Vir': 'Virgo', 'Sex': 'Sextans',
        'Aqr': 'Aquarius', 'Sgr': 'Sagittarius', 'CMa': 'Canis Major', 'Hya': 'Hydra',
        'Crv': 'Corvus', 'Scl': 'Sculptor', 'For': 'Fornax', 'CrA': 'Corona Australis',
        'Sco': 'Scorpius', 'Pup': 'Puppis', 'Col': 'Columba', 'Vel': 'Vela',
        'Cen': 'Centaurus', 'Ara': 'Ara', 'Hor': 'Horologium', 'Cir': 'Circinus',
        'Nor': 'Norma', 'Car': 'Carina', 'Pav': 'Pavo', 'Cru': 'Crux',
        'TrA': 'Triangulum Australe', 'Dor': 'Dorado', 'Tuc': 'Tucana', 'Mus': 'Musca',
        'Aps': 'Apus', 'Cha': 'Chamaeleon', 'Eri': 'Eridanus', 'Cnc': 'Cancer',
        'UMa': 'Ursa Major', 'Gru': 'Grus', 'Crt': 'Crater', 'Ori': 'Orion',
        'CrB': 'Corona Borealis', 'Psc': 'Pisces', 'Aql': 'Aquila', 'Ser': 'Serpens',
        'Phe': 'Phoenix', 'Lep': 'Lepus', 'Ari': 'Aries', 'Oph': 'Ophiuchus',
        'Her': 'Hercules', 'Cap': 'Capricornus', 'PsA': 'Piscis Austrinus',
        'CMi': 'Canis Minor', 'Equ': 'Equuleus', 'UMi': 'Ursa Minor', 'Tri': 'Triangulum',
        'Lib': 'Libra', 'Oct': 'Octans', 'LMi': 'Leo Minor', 'Sge': 'Sagitta', 'Lyr': 'Lyra'
    }
    
    return constellation_map.get(constellation_abbreviation, None)


def read_description_from_file(filename):
    full_path = os.path.join(observatiom_notes_dir, filename)

    try:
        with open(full_path, 'r', encoding='utf-8') as file:
            return file.read()
    except FileNotFoundError:
        return None

def extract_messier_objects(file):
    df = pd.read_csv(file)
    
    df['friendlyName'] = pd.NA
    
    df['ngcId'] = pd.NA
    df['objectId'] = 'M' + df['ObjectNum'].astype(str)
    
    df['ra'] = pd.NA
    df['dec'] = pd.NA
    
    df['observationNotes'] = pd.NA
    
    # Iterate through the rows of the DataFrame
    for index, row in df.iterrows():
        ngc_id, friendly_name = extract_ngc_id(row['Name'])

        if (friendly_name == None):
            friendly_name = get_friendly_name(ngc_id)
            
        if (friendly_name == None):
            friendly_name = df.at[index, 'objectId']
        
        df.at[index, 'friendlyName'] = friendly_name
        df.at[index, 'ngcId'] = ngc_id or pd.NA

        # RA and Dec collapse into coordinates column
        ra = (row['RAHour'] + row['RAMinute']/60) * 15
        df.at[index, 'ra'] = ra

        dec_sign = -1 if row['DecSign'].strip() == '-' else 1
        dec = dec_sign * (row['DecDeg'] + row['DecMinute']/60)
        df.at[index, 'dec'] = dec
        
        filename = f"m{row['ObjectNum']}.txt"
        observationNotes = read_description_from_file(filename)
        df.at[index, 'observationNotes'] = observationNotes or pd.NA

    df['Magnitude'] = df['Magnitude'].apply(convert_magnitude) 
    df['subType'] = df['Type']
    df['Type'] = df['Type'].apply(map_type)
        
    # Drop the original columns used to calculate RA and Dec
    df = df.drop(columns=['ObjectNum', 'Name', 'RAHour', 'RAMinute', 'DecSign', 'DecDeg', 'DecMinute', 'Info'])

    # Rename
    df.rename(columns={"Constellation": "constellation", "Magnitude": "magnitude", "Type": "type"}, inplace=True)

    
    # Reorder
    column_order = ['friendlyName', 'objectId', 'ngcId', 'ra', 'dec', 'type', 'subType', 'constellation', 'magnitude', 'observationNotes']
    df = df[column_order]
    
    return df

def extract_caldwell_objects(file):
    df = pd.read_csv(file)
    
    df['friendlyName'] = pd.NA

    df['ngcId'] = pd.NA
    df['objectId'] = 'C' + df['ObjectNum'].astype(str)
    
    df['ra'] = pd.NA
    df['dec'] = pd.NA
    
    df['observationNotes'] = pd.NA

    # Iterate through the rows of the DataFrame
    for index, row in df.iterrows():
        ngc_id, friendly_name = extract_ngc_id(row['Name'])

        if (friendly_name == None):
            friendly_name = get_friendly_name(ngc_id)
        
        df.at[index, 'friendlyName'] = friendly_name or pd.NA
        df.at[index, 'ngcId'] = ngc_id or pd.NA

        if (friendly_name == None):
            friendly_name = ngc_id or df.at[index, 'objectId']
        
        df.at[index, 'friendlyName'] = friendly_name
        df.at[index, 'ngcId'] = ngc_id or pd.NA

        # RA and Dec collapse into coordinates column
        ra = (row['RAHour'] + row['RAMinute']/60) * 15
        df.at[index, 'ra'] = ra

        dec_sign = -1 if row['DecSign'].strip() == '-' else 1
        dec = dec_sign * (row['DecDeg'] + row['DecMinute']/60)
        df.at[index, 'dec'] = dec  
    
        filename = f"caldwell{row['ObjectNum']}.txt"
        observationNotes = read_description_from_file(filename)
        df.at[index, 'observationNotes'] = observationNotes or pd.NA    
    
    df['Constellation'] = df['Constellation'].apply(map_constellation)
    df['Magnitude'] = df['Magnitude'].apply(convert_magnitude) 
    df['subType'] = df['Type']
    df['Type'] = df['Type'].apply(map_type)
    
    # Drop the original columns used to calculate RA and Dec
    df = df.drop(columns=['ObjectNum', 'Name', 'RAHour', 'RAMinute', 'DecSign', 'DecDeg', 'DecMinute', 'Info'])

    # Rename
    df.rename(columns={"Constellation": "constellation", "Magnitude": "magnitude", "Type": "type"}, inplace=True)
    
    # Reorder
    column_order = ['friendlyName', 'objectId', 'ngcId', 'ra', 'dec', 'type', 'subType', 'constellation', 'magnitude', 'observationNotes']
    df = df[column_order]
    
    return df
    
def ra_to_decimal(hours, minutes, seconds):
    return (hours + minutes / 60 + seconds / 3600) * 15

def dec_to_decimal(degrees, arcminutes, arcseconds, sign='+'):
    dec = degrees + arcminutes / 60 + arcseconds / 3600
    return dec if sign == '+' else -dec

def create_dso():
    column_order = ['friendlyName', 'objectId', 'ngcId', 'ra', 'dec', 'type', 'subType', 'constellation', 'magnitude', 'observationNotes']
    df = pd.DataFrame(columns=column_order)

    dsos = [
        {
            'friendlyName': "Hoag's Object",
            'objectId': 'hoag',
            'ngcId': 'PGC 54559',
            'ra': ra_to_decimal(15, 17, 14.4),
            'dec': dec_to_decimal(21, 35, 8),
            'type': 'galaxy',
            'subType': 'Ring Galaxy',
            'constellation': 'Serpens',
            'magnitude': 16.0,
            'observationNotes': pd.NA
        }
    ]

    df = pd.concat([df, pd.DataFrame(dsos)], ignore_index=True)

    return df

In [3]:
df_dso = create_dso()
df_dso[0:10]

,friendlyName,objectId,ngcId,ra,dec,type,subType,constellation,magnitude,observationNotes
0,Hoag's Object,hoag,PGC 54559,229.310000,21.585556,galaxy,Ring Galaxy,Serpens,16.000000,<NA>

In [4]:
file = "MessierObjects.csv"
df_messier = extract_messier_objects(file)
df_messier[0:200]

,friendlyName,objectId,ngcId,ra,dec,type,subType,constellation,magnitude,observationNotes
0,Crab Nebula,M1,NGC 1952,83.625000,22.016667,nebula,Supernova Remnant,Taurus,8.400000,"The Crab Nebula, or M1, is a supernova remnant..."
1,M2,M2,NGC 7089,323.375000,-0.816667,cluster,Globular Cluster,Aquarius,6.500000,<NA>
2,M3,M3,NGC 5272,205.550000,28.383333,cluster,Globular Cluster,Canes Venatici,6.200000,<NA>
3,M4,M4,NGC 6121,245.900000,-26.533333,cluster,Globular Cluster,Scorpius,5.600000,<NA>
4,M5,M5,NGC 5904,229.650000,2.083333,cluster,Globular Cluster,Serpens Caput,5.600000,<NA>
5,Butterfly Cluster,M6,NGC 6405,265.025000,-32.216667,cluster,Open Cluster,Scorpius,5.300000,"M6, also known as the Butterfly Cluster, is an..."
6,Ptolemy¹s Cluster,M7,NGC 6475,268.475000,-34.816667,cluster,Open Cluster,Scorpius,4.100000,"M7, known as the Ptolemy Cluster, is a promine..."
7,Lagoon Nebula,M8,NGC 6523,270.950000,-24.383333,nebula,Diffuse Nebula,Sagittarius,6.000000,"The Lagoon Nebula, or M8, is a large and brigh..."
8,M9,M9,NGC 6333,259.800000,-18.516667,cluster,Globular Cluster,Ophiucus,7.700000,<NA>
9,M10,M10,NGC 6254,254.275000,-4.100000,cluster,Globular Cluster,Ophiucus,6.600000,<NA>
10,Wild Duck Cluster,M11,NGC 6705,282.775000,-6.266667,cluster,Open Cluster,Scutum,6.300000,"M11, or the Wild Duck Cluster, is an open clus..."
11,M12,M12,NGC 6218,251.800000,-1.950000,cluster,Globular Cluster,Ophiucus,6.700000,<NA>
12,Hercules Globular Cluster,M13,NGC 6205,250.425000,36.466667,cluster,Globular Cluster,Hercules,5.800000,"M13, the Great Globular Cluster in Hercules, i..."
13,M14,M14,NGC 6402,264.400000,-3.250000,cluster,Globular Cluster,Ophiucus,7.600000,<NA>
14,M15,M15,NGC 7078,322.500000,12.166667,cluster,Globular Cluster,Pegasus,6.200000,<NA>
15,Eagle Nebula Cluster,M16,NGC 6611,274.700000,-13.783333,cluster,Open Cluster,Serpens Claudia,6.400000,"The Eagle Nebula, or M16, is a young open clus..."
16,"Omega, Swan, Horseshoe Nebula",M17,NGC 6618,275.200000,-16.183333,nebula,Diffuse Nebula,Sagittarius,7.000000,"M17, also known as the Omega Nebula or the Swa..."
17,M18,M18,NGC 6613,274.975000,-17.133333,cluster,Open Cluster,Sagittarius,7.500000,<NA>
18,M19,M19,NGC 6273,255.650000,-26.266667,cluster,Globular Cluster,Ophiucus,6.800000,<NA>
19,Trifid Nebula,M20,NGC 6514,270.575000,-23.033333,nebula,Diffuse Nebula,Sagittarius,9.000000,<NA>
20,M21,M21,NGC 6531,271.150000,-22.500000,cluster,Open Cluster,Sagittarius,6.500000,<NA>
21,M22,M22,NGC 6656,279.100000,-23.900000,cluster,Globular Cluster,Sagittarius,5.100000,"M22, near the top of the 'teapot' in Sagittari..."
22,M23,M23,NGC 6494,269.200000,-19.016667,cluster,Open Cluster,Sagittarius,6.900000,<NA>
23,Milky Way Patch,M24,NGC 6603,274.600000,-18.416667,star,Star Cloud,Sagittarius,4.600000,<NA>
24,IC 4725,M25,<NA>,277.925000,-19.233333,cluster,Open Cluster,Sagittarius,6.500000,<NA>
25,M26,M26,NGC 6694,281.300000,-9.400000,cluster,Open Cluster,Scutum,8.000000,<NA>
26,Dumbbell Nebula,M27,NGC 6853,299.900000,22.716667,nebula,Planetary Nebula,Vulpecula,7.400000,"M27, known as the Dumbbell Nebula, is a bright..."
27,M28,M28,NGC 6626,276.125000,-24.866667,cluster,Globular Cluster,Sagittarius,6.800000,<NA>
28,M29,M29,NGC 6913,305.975000,38.533333,cluster,Open Cluster,Cygnus,7.100000,<NA>
29,M30,M30,NGC 7099,325.100000,-23.183333,cluster,Globular Cluster,Capricornus,7.200000,<NA>
30,Andromeda Galaxy,M31,NGC 224,10.675000,41.266667,galaxy,Spiral Galaxy,Andromeda,3.400000,"The Andromeda Galaxy, known as M31, is one of ..."
31,Satellite of M31,M32,NGC 221,10.675000,40.866667,galaxy,Elliptical Galaxy,Andromeda,8.100000,<NA>
32,Triangulum/Pinwheel Galaxy,M33,NGC 598,23.475000,30.650000,galaxy,Spiral Galaxy,Triangulum,5.700000,<NA>
33,M34,M34,NGC 1039,40.500000,42.783333,cluster,Open Cluster,Perseus,5.500000,<NA>
34,M35,M35,NGC 2168,92.225000,24.333333,cluster,Open Cluster,Gemini,5.300000,<NA>
35,M36,M36,NGC 1960,84.025000,34.133333,cluster,Open Cluster,Auriga,6.300000,<NA>
36,M37,M37,NGC 2099,88.100000,32.550000,cluster,Open Cluster,Auriga,6.200000,<NA>
37,M38,M38,NGC 1912,82.175000,35.833333,cluster,Open Cluster,Auriga,7.400000,<NA>
38,M39,M39,NGC 7092,323.050000,48.433333,cluster,Open Cluster,Cygnus,5.200000,<NA>
39,Winecke 4,M40,<NA>,185.550000,58.083333,star,Double Star,Ursa Major,<NA>,<NA>
40,M41,M41,NGC 2287,101.750000,-20.733333,cluster,Open Cluster,Canis Major,4.600000,<NA>
41,Great Orion Nebula,M42,NGC 1976,83.850000,-5.450000,nebula,Diffuse Nebula,Orion,4.000000,"The Orion Nebula, or M42, is a diffuse nebula ..."
42,de Mairan¹s Nebula,M43,NGC 1982,83.900000,-5.266667,nebula,Diffuse Nebula,Orion,9.000000,<NA>
43,Beehive Cluster (Praesepe),M44,NGC 2632,130.025000,19.983333,cluster,Open Cluster,Cancer,3.700000,<NA>
44,"Pleiades, Subaru, Seven Sisters",M45,<NA>,56.750000,24.120000,cluster,Open Cluster,Taurus,1.600000,"M45, commonly known as the Pleiades or the Sev..."
45,M46,M46,NGC 2437,115.450000,-14.816667,cluster,Open Cluster,Puppis,6.000000,<NA>
46,M47,M47,NGC 2422,114.150000,-14.500000,cluster,Open Cluster,Puppis,5.200000,<NA>
47,M48,M48,NGC 2548,123.450000,-5.800000,cluster,Open Cluster,Hydra,5.500000,<NA>
48,M49,M49,NGC 4472,187.450000,8.000000,galaxy,Elliptical Galaxy,Virgo,8.400000,<NA>
49,M50,M50,NGC 2323,105.800000,-8.333333,cluster,Open Cluster,Monocerus,6.300000,<NA>
50,Whirlpool Galaxy,M51,NGC 5194,202.475000,47.200000,galaxy,Spiral Galaxy,Canes Venatici,8.400000,"M51, also known as the Whirlpool Galaxy, is a ..."
51,M52,M52,NGC 7654,351.050000,61.583333,cluster,Open Cluster,Cassiopeia,7.300000,<NA>
52,M53,M53,NGC 5024,198.225000,18.166667,cluster,Globular Cluster,Coma Berenices,7.600000,<NA>
53,M54,M54,NGC 6715,283.775000,-30.483333,cluster,Globular Cluster,Sagittarius,7.600000,<NA>
54,M55,M55,NGC 6809,295.000000,-30.966667,cluster,Globular Cluster,Sagittarius,6.300000,<NA>
55,M56,M56,NGC 6779,289.150000,30.183333,cluster,Globular Cluster,Lyra,8.300000,<NA>
56,Ring Nebula,M57,NGC 6720,283.400000,33.033333,nebula,Planetary Nebula,Lyra,8.800000,"M57, the Ring Nebula, is a planetary nebula in..."
57,M58,M58,NGC 4579,189.425000,11.816667,galaxy,Spiral Galaxy,Virgo,9.700000,<NA>
58,M59,M59,NGC 4621,190.500000,11.650000,galaxy,Elliptical Galaxy,Virgo,9.600000,<NA>
59,M60,M60,NGC 4649,190.925000,11.550000,galaxy,Elliptical Galaxy,Virgo,8.800000,<NA>
60,M61,M61,NGC 4303,185.475000,4.466667,galaxy,Spiral Galaxy,Virgo,9.700000,<NA>
61,M62,M62,NGC 6266,255.300000,-30.116667,cluster,Globular Cluster,Ophiucus,6.500000,<NA>
62,Sunflower Galaxy,M63,NGC 5055,198.950000,42.033333,galaxy,Spiral Galaxy,Canes Venatici,8.600000,<NA>
63,Blackeye Galaxy,M64,NGC 4826,194.175000,21.683333,galaxy,Spiral Galaxy,Coma Berenices,8.500000,<NA>
64,M65,M65,NGC 3623,169.725000,13.083333,galaxy,Spiral Galaxy,Leo,9.300000,<NA>
65,M66,M66,NGC 3627,170.050000,12.983333,galaxy,Spiral Galaxy,Leo,8.900000,<NA>
66,M67,M67,NGC 2682,132.600000,11.816667,cluster,Open Cluster,Cancer,6.100000,<NA>
67,M68,M68,NGC 4590,189.875000,-26.750000,cluster,Globular Cluster,Hydra,7.800000,<NA>
68,M69,M69,NGC 6637,277.850000,-32.350000,cluster,Globular Cluster,Sagittarius,7.600000,<NA>
69,M70,M70,NGC 6681,280.800000,-32.300000,cluster,Globular Cluster,Sagittarius,7.900000,<NA>
70,M71,M71,NGC 6838,298.450000,18.783333,cluster,Globular Cluster,Sagitta,8.300000,<NA>
71,M72,M72,NGC 6981,313.375000,-12.533333,cluster,Globular Cluster,Aquarius,9.300000,<NA>
72,Group of 4 stars,M73,NGC 6994,314.750000,-12.633333,star,Group/Asterism,Aquarius,9.000000,<NA>
73,M74,M74,NGC 628,24.175000,15.783333,galaxy,Spiral Galaxy,Pisces,9.400000,<NA>
74,M75,M75,NGC 6864,301.525000,-21.916667,cluster,Globular Cluster,Sagittarius,8.500000,<NA>
75,"Little Dumbell, Cork, Butterfly Nebula",M76,NGC 650,25.575000,51.566667,nebula,Planetary Nebula,Perseus,10.100000,<NA>
76,Cetus A,M77,NGC 1068,40.675000,0.016667,galaxy,Spiral Galaxy,Cetus,8.900000,<NA>
77,M78,M78,NGC 2068,86.675000,0.050000,nebula,Diffuse Nebula,Orion,8.300000,<NA>
78,M79,M79,NGC 1904,81.125000,-24.550000,cluster,Globular Cluster,Lepus,7.700000,<NA>
79,M80,M80,NGC 6093,244.250000,-22.983333,cluster,Globular Cluster,Scorpius,7.300000,<NA>
80,Bode¹s Galaxy,M81,NGC 3031,148.900000,69.066667,galaxy,Spiral Galaxy,Ursa Major,6.900000,"M81, or Bode's Galaxy, is a grand design spira..."
81,Cigar Galaxy,M82,NGC 3034,148.950000,69.683333,galaxy,Irregular Galaxy,Ursa Major,8.400000,"M82, the Cigar Galaxy, is a starburst galaxy n..."
82,Southern Pinwheel Galaxy,M83,NGC 5236,204.250000,-29.866667,galaxy,Spiral Galaxy,Hydra,7.600000,<NA>
83,M84,M84,NGC 4374,186.275000,12.883333,galaxy,Lenticular (S0) Galaxy,Virgo,9.100000,<NA>
84,M85,M85,NGC 4382,186.350000,18.183333,galaxy,Lenticular (S0) Galaxy,Coma Berenices,9.100000,<NA>
85,FAUST V051,M86,NGC 4406,186.550000,12.950000,galaxy,Lenticular (S0) Galaxy,Virgo,8.900000,<NA>
86,Virgo A,M87,NGC 4486,187.700000,12.400000,galaxy,Elliptical Galaxy,Virgo,8.600000,<NA>
87,M88,M88,NGC 4501,188.000000,14.416667,galaxy,Spiral Galaxy,Coma Berenices,9.600000,<NA>
88,M89,M89,NGC 4552,188.925000,12.550000,galaxy,Elliptical Galaxy,Virgo,9.800000,<NA>
89,M90,M90,NGC 4569,189.200000,13.166667,galaxy,Spiral Galaxy,Virgo,9.500000,<NA>
90,M91,M91,NGC 4548,188.850000,14.500000,galaxy,Spiral Galaxy,Coma Berenices,10.200000,<NA>
91,M92,M92,NGC 6341,259.275000,43.133333,cluster,Globular Cluster,Hercules,6.400000,<NA>
92,M93,M93,NGC 2447,116.150000,-23.866667,cluster,Open Cluster,Puppis,6.000000,<NA>
93,M94,M94,NGC 4736,192.725000,41.116667,galaxy,Spiral Galaxy,Canes Venatici,8.200000,<NA>
94,M95,M95,NGC 3351,161.000000,11.700000,galaxy,Spiral Galaxy,Leo,9.700000,<NA>
95,M96,M96,NGC 3368,161.700000,11.816667,galaxy,Spiral Galaxy,Leo,9.200000,<NA>
96,Owl Nebula,M97,NGC 3587,168.700000,55.016667,nebula,Planetary Nebula,Ursa Major,9.900000,<NA>
97,M98,M98,NGC 4192,183.450000,14.900000,galaxy,Spiral Galaxy,Coma Berenices,10.100000,<NA>
98,Virgo Cluster Pinwheel,M99,NGC 4254,184.700000,14.416667,galaxy,Spiral Galaxy,Coma Berenices,9.900000,<NA>
99,M100,M100,NGC 4321,185.725000,15.816667,galaxy,Spiral Galaxy,Coma Berenices,9.300000,<NA>
100,Pinwheel Galaxy,M101,NGC 5457,210.800000,54.350000,galaxy,Spiral Galaxy,Ursa Major,7.900000,<NA>
101,Spindle Galaxy,M102,NGC 5866,226.625000,55.766667,galaxy,Lenticular (S0) Galaxy,Draco,9.900000,<NA>
102,M103,M103,NGC 581,23.300000,60.700000,cluster,Open Cluster,Cassiopeia,7.400000,<NA>
103,Sombrero Galaxy,M104,NGC 4594,190.000000,-11.616667,galaxy,Spiral Galaxy,Virgo,8.000000,<NA>
104,M105,M105,NGC 3379,161.950000,12.583333,galaxy,Elliptical Galaxy,Leo,9.300000,<NA>
105,M106,M106,NGC 4258,184.750000,47.300000,galaxy,Spiral Galaxy,Canes Venatici,8.400000,<NA>
106,M107,M107,NGC 6171,248.125000,-13.050000,cluster,Globular Cluster,Ophiucus,7.900000,<NA>
107,M108,M108,NGC 3556,167.875000,55.666667,galaxy,Spiral Galaxy,Ursa Major,10.000000,<NA>
108,M109,M109,NGC 3992,179.400000,53.383333,galaxy,Spiral Galaxy,Ursa Major,9.800000,<NA>
109,Satellite of M31,M110,NGC 205,10.100000,41.683333,galaxy,Elliptical Galaxy,Andromeda,8.500000,<NA>

In [5]:
file = "CaldwellObjects.csv"
df_caldwell = extract_caldwell_objects(file)


# Provide some friendly names not provided by Simbad
df_caldwell.loc[df_caldwell['objectId'] == "C2", "friendlyName"] = "Bow-Tie Nebula"
df_caldwell.loc[df_caldwell['objectId'] == "C5", "friendlyName"] = "Hidden Galaxy"
df_caldwell.loc[df_caldwell['objectId'] == "C6", "friendlyName"] = "Cat's Eye Nebula"
df_caldwell.loc[df_caldwell['objectId'] == "C9", "friendlyName"] = "Cave Nebula"
df_caldwell.loc[df_caldwell['objectId'] == "C12", "friendlyName"] = "Fireworks Galaxy"
df_caldwell.loc[df_caldwell['objectId'] == "C14", "friendlyName"] = "Double Cluster (h&X Persei)"
df_caldwell.loc[df_caldwell['objectId'] == "C19", "friendlyName"] = "Cocoon Nebula"
df_caldwell.loc[df_caldwell['objectId'] == "C23", "friendlyName"] = "Silver Sliver Galaxy"
df_caldwell.loc[df_caldwell['objectId'] == "C31", "friendlyName"] = "Flaming Star Nebula"
df_caldwell.loc[df_caldwell['objectId'] == "C33", "friendlyName"] = "East Veil"
df_caldwell.loc[df_caldwell['objectId'] == "C34", "friendlyName"] = "West Veil"
df_caldwell.loc[df_caldwell['objectId'] == "C35", "friendlyName"] = "Coma B"
df_caldwell.loc[df_caldwell['objectId'] == "C38", "friendlyName"] = "Needle Galaxy"
df_caldwell.loc[df_caldwell['objectId'] == "C39", "friendlyName"] = "Eskimo/Clown Face Nebula"
df_caldwell.loc[df_caldwell['objectId'] == "C41", "friendlyName"] = "Hyades Cluster"
df_caldwell.loc[df_caldwell['objectId'] == "C46", "friendlyName"] = "Hubble's Variable Nebula"
df_caldwell.loc[df_caldwell['objectId'] == "C49", "friendlyName"] = "Rosette Nebula"
df_caldwell.loc[df_caldwell['objectId'] == "C50", "friendlyName"] = "Satellite Cluster"
df_caldwell.loc[df_caldwell['objectId'] == "C56", "friendlyName"] = "Skull Nebula"
df_caldwell.loc[df_caldwell['objectId'] == "C60", "friendlyName"] = "Antennae Galaxies"
df_caldwell.loc[df_caldwell['objectId'] == "C61", "friendlyName"] = "Antennae Galaxies" # same as C60
df_caldwell.loc[df_caldwell['objectId'] == "C68", "friendlyName"] = "R CrA Nebula"
df_caldwell.loc[df_caldwell['objectId'] == "C80", "friendlyName"] = "Omega Centauri"
df_caldwell.loc[df_caldwell['objectId'] == "C85", "friendlyName"] = "Omicron Velorum Cluster"
df_caldwell.loc[df_caldwell['objectId'] == "C89", "friendlyName"] = "S Normae Cluster"
df_caldwell.loc[df_caldwell['objectId'] == "C91", "friendlyName"] = "Wishing Well Culster"
df_caldwell.loc[df_caldwell['objectId'] == "C92", "friendlyName"] = "Eta Carinae Nebula"
df_caldwell.loc[df_caldwell['objectId'] == "C93", "friendlyName"] = "Great Peacock Globular"
df_caldwell.loc[df_caldwell['objectId'] == "C96", "friendlyName"] = "Southern Beehive Cluster"
df_caldwell.loc[df_caldwell['objectId'] == "C97", "friendlyName"] = "Pearl Cluster"
df_caldwell.loc[df_caldwell['objectId'] == "C99", "friendlyName"] = "Coalsack Nebula"
df_caldwell.loc[df_caldwell['objectId'] == "C100", "friendlyName"] = "Lambda Centauri Nebula"
df_caldwell.loc[df_caldwell['objectId'] == "C102", "friendlyName"] = "Theta Car Cluster"
df_caldwell.loc[df_caldwell['objectId'] == "C103", "friendlyName"] = "Tarantula Nebula"


df_caldwell[0:200]

,friendlyName,objectId,ngcId,ra,dec,type,subType,constellation,magnitude,observationNotes
0,NGC 188,C1,NGC 188,11.100000,85.333333,cluster,Open Cluster,Cepheus,8.100000,caldwell 1 data
1,Bow-Tie Nebula,C2,NGC 40,3.250000,72.533333,nebula,Planetary Nebula,Cepheus,12.400000,<NA>
2,NGC 4236,C3,NGC 4236,184.175000,69.466667,galaxy,Spiral Galaxy,Draco,9.700000,<NA>
3,IRIS Nebula,C4,NGC 7023,315.450000,68.200000,nebula,Bright Nebula,Cepheus,<NA>,<NA>
4,Hidden Galaxy,C5,<NA>,56.700000,68.100000,galaxy,Spiral Galaxy,Camelopardalis,9.200000,<NA>
5,Cat's Eye Nebula,C6,NGC 6543,269.650000,66.633333,nebula,Planetary Nebula,Draco,8.100000,<NA>
6,NGC 2403,C7,NGC 2403,114.225000,65.600000,galaxy,Spiral Galaxy,Camelopardalis,8.400000,<NA>
7,NGC 559,C8,NGC 559,22.375000,63.300000,cluster,Open Cluster,Cassiopeia,9.500000,<NA>
8,Cave Nebula,C9,<NA>,344.200000,62.616667,nebula,Bright Nebula,Cepheus,<NA>,<NA>
9,NGC 663,C10,NGC 663,26.500000,61.250000,cluster,Open Cluster,Cassiopeia,7.100000,<NA>
10,Bubble Nebula,C11,NGC 7635,350.175000,61.200000,nebula,Bright Nebula,Cassiopeia,<NA>,<NA>
11,Fireworks Galaxy,C12,NGC 6946,308.700000,60.150000,galaxy,Spiral Galaxy,Cepheus,8.900000,<NA>
12,Owl Cluster,C13,NGC 457,19.775000,58.333333,cluster,Open Cluster,Cassiopeia,6.400000,<NA>
13,Double Cluster (h&X Persei),C14,NGC 869,35.000000,57.133333,cluster,Open Cluster,Perseus,4.300000,"Caldwell 14, also known as the Double Cluster,..."
14,Blinking Planetary,C15,NGC 6826,296.200000,50.516667,nebula,Planetary Nebula,Cygnus,8.800000,<NA>
15,NGC 7243,C16,NGC 7243,333.825000,49.883333,cluster,Open Cluster,Lacerta,6.400000,<NA>
16,NGC 147,C17,NGC 147,8.300000,48.500000,galaxy,Elliptical Galaxy,Cassiopeia,9.300000,<NA>
17,NGC 185,C18,NGC 185,9.750000,48.333333,galaxy,Elliptical Galaxy,Cassiopeia,9.200000,<NA>
18,Cocoon Nebula,C19,<NA>,328.375000,47.266667,nebula,Bright Nebula,Cygnus,<NA>,<NA>
19,North America Nebula,C20,NGC 7000,314.700000,44.333333,nebula,Bright Nebula,Cygnus,<NA>,<NA>
20,NGC 4449,C21,NGC 4449,187.050000,44.100000,galaxy,Irregular Galaxy,Canes Venatici,9.400000,<NA>
21,Copeland's Blue Snowball,C22,NGC 7662,351.475000,42.550000,nebula,Planetary Nebula,Andromeda,8.300000,<NA>
22,Silver Sliver Galaxy,C23,NGC 891,35.650000,42.350000,galaxy,Spiral Galaxy,Andromeda,9.900000,<NA>
23,Perseus A,C24,NGC 1275,49.950000,41.516667,galaxy,Irregular Galaxy,Perseus,11.600000,<NA>
24,NGC 2419,C25,NGC 2419,114.525000,38.883333,cluster,Globular Cluster,Lynx,10.400000,<NA>
25,NGC 4244,C26,NGC 4244,184.375000,37.816667,galaxy,Spiral Galaxy,Canes Venatici,10.200000,<NA>
26,Crescent Nebula,C27,NGC 6888,303.000000,38.350000,nebula,Bright Nebula,Cygnus,<NA>,<NA>
27,NGC 752,C28,NGC 752,29.450000,37.683333,cluster,Open Cluster,Andromeda,5.700000,<NA>
28,NGC 5005,C29,NGC 5005,197.725000,37.050000,galaxy,Spiral Galaxy,Canes Venatici,9.800000,<NA>
29,NGC 7331,C30,NGC 7331,339.275000,34.416667,galaxy,Spiral Galaxy,Pegasus,9.500000,<NA>
30,Flaming Star Nebula,C31,<NA>,79.050000,34.266667,nebula,Bright Nebula,Auriga,<NA>,<NA>
31,Whale Galaxy,C32,NGC 4631,190.525000,32.533333,galaxy,Spiral Galaxy,Canes Venatici,9.300000,<NA>
32,East Veil,C33,NGC 6992,314.100000,31.716667,nebula,Supernova Remnant,Cygnus,<NA>,"Caldwell 33, located in Draco, is a spiral gal..."
33,West Veil,C34,NGC 6960,311.425000,30.716667,nebula,Supernova Remnant,Cygnus,<NA>,"Caldwell 34, part of the Veil Nebula, is a sup..."
34,Coma B,C35,NGC 4889,195.025000,27.983333,galaxy,Elliptical Galaxy,Coma Berenices,11.400000,<NA>
35,NGC 4559,C36,NGC 4559,189.000000,27.966667,galaxy,Spiral Galaxy,Coma Berenices,9.800000,<NA>
36,NGC 6885,C37,NGC 6885,303.000000,26.483333,cluster,Open Cluster,Vulpecula,5.900000,<NA>
37,Needle Galaxy,C38,NGC 4565,189.075000,25.983333,galaxy,Spiral Galaxy,Coma Berenices,9.600000,<NA>
38,Eskimo/Clown Face Nebula,C39,NGC 2392,112.300000,20.916667,nebula,Planetary Nebula,Gemini,9.200000,<NA>
39,NGC 3626,C40,NGC 3626,170.025000,18.350000,galaxy,Spiral Galaxy,Leo,10.900000,<NA>
40,Hyades Cluster,C41,<NA>,66.750000,16.000000,cluster,Open Cluster,Taurus,0.500000,<NA>
41,NGC 7006,C42,NGC 7006,315.375000,16.183333,cluster,Globular Cluster,Delphinus,10.600000,<NA>
42,NGC 7814,C43,NGC 7814,0.825000,16.150000,galaxy,Spiral Galaxy,Pegasus,10.500000,<NA>
43,NGC 7479,C44,NGC 7479,346.225000,12.316667,galaxy,Spiral Galaxy,Pegasus,11.000000,<NA>
44,NGC 5248,C45,NGC 5248,204.375000,8.883333,galaxy,Spiral Galaxy,Bootes,10.200000,<NA>
45,Hubble's Variable Nebula,C46,NGC 2261,99.800000,8.733333,nebula,Bright Nebula,Monoceros,<NA>,<NA>
46,NGC 6934,C47,NGC 6934,308.550000,7.400000,cluster,Globular Cluster,Delphinus,8.900000,<NA>
47,NGC 2775,C48,NGC 2775,137.575000,7.033333,galaxy,Spiral Galaxy,Canes Major,10.300000,<NA>
48,Rosette Nebula,C49,NGC 2237,98.075000,5.050000,nebula,Bright Nebula,Monoceros,<NA>,"Caldwell 49, known as the Rosette Nebula, is a..."
49,Satellite Cluster,C50,NGC 2244,98.100000,4.866667,cluster,Open Cluster,Monoceros,4.800000,<NA>
50,IC 1613,C51,<NA>,16.200000,2.116667,galaxy,Irregular Galaxy,Cetus,9.300000,<NA>
51,NGC 4697,C52,NGC 4697,192.150000,-5.800000,galaxy,Elliptical Galaxy,Virgo,9.300000,<NA>
52,Spindle Galaxy,C53,NGC 3115,151.300000,-7.716667,galaxy,Elliptical Galaxy,Sextans,9.100000,<NA>
53,NGC 2506,C54,NGC 2506,120.050000,-10.783333,cluster,Open Cluster,Monoceros,7.600000,<NA>
54,Saturn Nebula,C55,NGC 7009,316.050000,-11.366667,nebula,Planetary Nebula,Aquarius,8.000000,<NA>
55,Skull Nebula,C56,NGC 246,11.750000,-11.883333,nebula,Planetary Nebula,Cetus,10.900000,<NA>
56,Barnard's Galaxy,C57,NGC 6822,296.225000,-14.800000,galaxy,Irregular Galaxy,Sagittarius,8.800000,<NA>
57,Caroline's Cluster,C58,NGC 2360,109.450000,-15.616667,cluster,Open Cluster,Canis Major,7.200000,<NA>
58,Jupiter's Ghost Nebula,C59,NGC 3242,156.200000,-18.633333,nebula,Planetary Nebula,Hydra,7.800000,<NA>
59,Antennae Galaxies,C60,NGC 4038,180.475000,-18.866667,galaxy,Spiral Galaxy,Corvus,10.700000,<NA>
60,Antennae Galaxies,C61,NGC 4039,180.475000,-18.883333,galaxy,Spiral Galaxy,Corvus,10.700000,<NA>
61,NGC 247,C62,NGC 247,11.775000,-20.766667,galaxy,Spiral Galaxy,Cetus,9.100000,<NA>
62,Helix Nebula,C63,NGC 7293,337.400000,-20.800000,nebula,Planetary Nebula,Aquarius,7.300000,<NA>
63,Tau CMa,C64,NGC 2362,109.700000,-24.950000,cluster,Open Cluster,Canis Major,4.100000,"Caldwell 64, the Black Eye Galaxy or M64, is a..."
64,Sculptor Filament,C65,NGC 253,11.900000,-25.283333,galaxy,Spiral Galaxy,Sculptor,7.100000,<NA>
65,NGC 5694,C66,NGC 5694,219.900000,-26.533333,cluster,Globular Cluster,Hydra,10.200000,<NA>
66,NGC 1097,C67,NGC 1097,41.575000,-30.283333,galaxy,Spiral Galaxy,Fornax,9.200000,<NA>
67,R CrA Nebula,C68,NGC 6729,285.475000,-36.950000,nebula,Bright Nebula,Corona Australis,<NA>,<NA>
68,Bug Nebula,C69,NGC 6302,258.425000,-37.100000,nebula,Planetary Nebula,Scorpius,9.600000,<NA>
69,NGC 300,C70,NGC 300,13.725000,-37.683333,galaxy,Spiral Galaxy,Sculptor,8.700000,<NA>
70,NGC 2477,C71,NGC 2477,118.075000,-38.550000,cluster,Open Cluster,Puppis,5.800000,<NA>
71,NGC 55,C72,NGC 55,3.725000,-39.183333,galaxy,Spiral Galaxy,Sculptor,7.900000,<NA>
72,NGC 1851,C73,NGC 1851,78.525000,-40.050000,cluster,Globular Cluster,Columba,7.300000,<NA>
73,Eight-Burst Nebula,C74,NGC 3132,151.925000,-40.433333,nebula,Planetary Nebula,Vela,9.400000,<NA>
74,NGC 6124,C75,NGC 6124,246.400000,-40.666667,cluster,Open Cluster,Scorpius,5.800000,<NA>
75,NGC 6231,C76,NGC 6231,253.500000,-41.800000,cluster,Open Cluster,Scorpius,2.600000,<NA>
76,Centaurus A,C77,NGC 5128,201.375000,-43.016667,galaxy,Elliptical Galaxy,Centaurus,7.000000,<NA>
77,NGC 6541,C78,NGC 6541,272.000000,-43.700000,cluster,Globular Cluster,Corona Australis,6.600000,<NA>
78,NGC 3201,C79,NGC 3201,154.400000,-46.416667,cluster,Globular Cluster,Vela,6.700000,<NA>
79,Omega Centauri,C80,NGC 5139,201.700000,-47.483333,cluster,Globular Cluster,Centaurus,3.600000,<NA>
80,NGC 6352,C81,NGC 6352,261.375000,-48.416667,cluster,Globular Cluster,Ara,8.100000,<NA>
81,NGC 6193,C82,NGC 6193,250.325000,-48.766667,cluster,Open Cluster,Ara,5.200000,<NA>
82,NGC 4945,C83,NGC 4945,196.350000,-49.466667,galaxy,Spiral Galaxy,Centaurus,8.700000,<NA>
83,NGC 5286,C84,NGC 5286,206.600000,-51.366667,cluster,Globular Cluster,Centaurus,7.600000,<NA>
84,Omicron Velorum Cluster,C85,<NA>,130.050000,-53.066667,cluster,Open Cluster,Vela,2.500000,<NA>
85,NGC 6397,C86,NGC 6397,265.175000,-53.666667,cluster,Globular Cluster,Ara,5.600000,<NA>
86,NGC 1261,C87,NGC 1261,48.075000,-55.216667,cluster,Globular Cluster,Horologium,8.400000,<NA>
87,NGC 5823,C88,NGC 5823,226.425000,-55.600000,cluster,Open Cluster,Circinus,7.900000,<NA>
88,S Normae Cluster,C89,NGC 6087,244.725000,-57.900000,cluster,Open Cluster,Norma,5.400000,<NA>
89,NGC 2867,C90,NGC 2867,140.350000,-58.316667,nebula,Planetary Nebula,Carina,<NA>,<NA>
90,Wishing Well Culster,C91,NGC 3532,166.600000,-58.666667,cluster,Open Cluster,Carina,3.000000,<NA>
91,Eta Carinae Nebula,C92,NGC 3372,160.950000,-59.866667,nebula,Bright Nebula,Carina,<NA>,<NA>
92,Great Peacock Globular,C93,NGC 6752,287.725000,-59.983333,cluster,Globular Cluster,Pavo,5.400000,<NA>
93,Herschel's Jewel Box,C94,NGC 4755,193.400000,-60.333333,cluster,Open Cluster,Crux,4.200000,<NA>
94,NGC 6025,C95,NGC 6025,240.925000,-60.500000,cluster,Open Cluster,Triangulum Australe,5.100000,<NA>
95,Southern Beehive Cluster,C96,NGC 2516,119.575000,-60.866667,cluster,Open Cluster,Carina,3.800000,<NA>
96,Pearl Cluster,C97,NGC 3766,174.025000,-61.616667,cluster,Open Cluster,Centaurus,5.300000,<NA>
97,Coalsack Cluster,C98,NGC 4609,190.575000,-62.966667,cluster,Open Cluster,Crux,6.900000,<NA>
98,Coalsack Nebula,C99,<NA>,193.250000,-63.000000,nebula,Dark Nebula,Crux,<NA>,<NA>
99,Lambda Centauri Nebula,C100,<NA>,174.150000,-63.033333,cluster,Open Cluster,Centaurus,4.500000,<NA>
100,NGC 6744,C101,NGC 6744,287.450000,-63.850000,galaxy,Spiral Galaxy,Pavo,8.300000,<NA>
101,Theta Car Cluster,C102,<NA>,160.800000,-64.400000,cluster,Open Cluster,Carina,1.900000,<NA>
102,Tarantula Nebula,C103,NGC 2070,84.675000,-69.100000,nebula,Bright Nebula,Dorado,<NA>,<NA>
103,NGC 362,C104,NGC 362,15.800000,-70.850000,cluster,Globular Cluster,Tucana,6.600000,"Caldwell 104, also known as the Sombrero Galax..."
104,NGC 4833,C105,NGC 4833,194.900000,-70.883333,cluster,Globular Cluster,Musca,7.300000,<NA>
105,47 Tuc Cluster,C106,NGC 104,6.025000,-72.083333,cluster,Globular Cluster,Tucana,4.000000,<NA>
106,NGC 6101,C107,NGC 6101,246.450000,-72.200000,cluster,Globular Cluster,Apus,9.300000,<NA>
107,NGC 4372,C108,NGC 4372,186.450000,-72.666667,cluster,Globular Cluster,Musca,7.800000,<NA>
108,NGC 3195,C109,NGC 3195,152.375000,-80.866667,nebula,Planetary Nebula,Chamaeleon,<NA>,<NA>

In [6]:
df_combined = pd.concat([df_dso, df_messier, df_caldwell], ignore_index=True)

df_combined['id'] = 0
df_combined['recommended'] = False
df_combined['tags'] = ''

In [7]:
df_combined['type'].value_counts()

cluster    102
galaxy      76
nebula      39
star         3
Name: type, dtype: int64

In [8]:
df_combined.loc[df_combined['ngcId'] == "PGC 54559", 'recommended'] = True  # Crab Nebula
df_combined.loc[df_combined['ngcId'] == "PGC 54559", 'tags'] = "f/6.3" 

df_combined.loc[df_combined['objectId'] == "M1", 'recommended'] = True  # Crab Nebula
df_combined.loc[df_combined['objectId'] == "M1", 'tags'] = "f/10; UHC" 

df_combined.loc[df_combined['objectId'] == "M6", 'recommended'] = True  # Butterfly Cluster
df_combined.loc[df_combined['objectId'] == "M6", 'tags'] = "f/10" 

df_combined.loc[df_combined['objectId'] == "M7", 'recommended'] = True  # Ptolemy's Cluster
df_combined.loc[df_combined['objectId'] == "M7", 'tags'] = "f/6.3" 

df_combined.loc[df_combined['objectId'] == "M8", 'recommended'] = True  # Lagoon Nebula
df_combined.loc[df_combined['objectId'] == "M8", 'tags'] = "f/6.3; UGC" 

df_combined.loc[df_combined['objectId'] == "M11", 'recommended'] = True  # Wild Duck Cluster
df_combined.loc[df_combined['objectId'] == "M11", 'tags'] = "f/10" 

df_combined.loc[df_combined['objectId'] == "M13", 'recommended'] = True  # Hercules Globular Cluster
df_combined.loc[df_combined['objectId'] == "M13", 'tags'] = "f/10" 

df_combined.loc[df_combined['objectId'] == "M16", 'recommended'] = True  # Eagle Nebula
df_combined.loc[df_combined['objectId'] == "M16", 'tags'] = "f/6.3; UHC" 

df_combined.loc[df_combined['objectId'] == "M17", 'recommended'] = True  # The Omega or Swan Nebula
df_combined.loc[df_combined['objectId'] == "M17", 'tags'] = "f/6.3; UHC" 

df_combined.loc[df_combined['objectId'] == "M22", 'recommended'] = True  # Sagittarius cluster
df_combined.loc[df_combined['objectId'] == "M22", 'tags'] = "f/10" 

df_combined.loc[df_combined['objectId'] == "M27", 'recommended'] = True  # Dumbell nebula
df_combined.loc[df_combined['objectId'] == "M27", 'tags'] = "f/10; UHC" 

df_combined.loc[df_combined['objectId'] == "M31", 'recommended'] = True  # Andromeda Galaxy
df_combined.loc[df_combined['objectId'] == "M31", 'tags'] = "f/6.3" 

df_combined.loc[df_combined['objectId'] == "M33", 'recommended'] = True  # Triangulum Galaxy
df_combined.loc[df_combined['objectId'] == "M33", 'tags'] = "f/6.3" 

df_combined.loc[df_combined['objectId'] == "M42", 'recommended'] = True  # Orion Nebula
df_combined.loc[df_combined['objectId'] == "M42", 'tags'] = "f/6.3; UHC" 

df_combined.loc[df_combined['objectId'] == "M43", 'recommended'] = True  # De Mairan's Nebula
df_combined.loc[df_combined['objectId'] == "M43", 'tags'] = "f/6.3; UHC" 

df_combined.loc[df_combined['objectId'] == "M44", 'recommended'] = True  # Beehive Cluster
df_combined.loc[df_combined['objectId'] == "M44", 'tags'] = "f/6.3; UHC" 

df_combined.loc[df_combined['objectId'] == "M45", 'recommended'] = True  # Pleaiades
df_combined.loc[df_combined['objectId'] == "M45", 'tags'] = "f/6.3" 

df_combined.loc[df_combined['objectId'] == "M51", 'recommended'] = True  # Whirlpool Galaxy
df_combined.loc[df_combined['objectId'] == "M51", 'tags'] = "f/10" 

df_combined.loc[df_combined['objectId'] == "M57", 'recommended'] = True  # The Ring Nebula
df_combined.loc[df_combined['objectId'] == "M57", 'tags'] = "f/10" 

df_combined.loc[df_combined['objectId'] == "M63", 'recommended'] = True  # Sunflower Galaxy
df_combined.loc[df_combined['objectId'] == "M63", 'tags'] = "f/10" 

df_combined.loc[df_combined['objectId'] == "M64", 'recommended'] = True  # Blackeye Galaxy
df_combined.loc[df_combined['objectId'] == "M64", 'tags'] = "f/10" 

df_combined.loc[df_combined['objectId'] == "M65", 'recommended'] = True  # Leo Triplet
df_combined.loc[df_combined['objectId'] == "M65", 'tags'] = "f/6.3 - Leo Triplet" 

df_combined.loc[df_combined['objectId'] == "M66", 'recommended'] = True  # Leo Triplet
df_combined.loc[df_combined['objectId'] == "M66", 'tags'] = "f/6.3 - Leo Triplet" 

df_combined.loc[df_combined['objectId'] == "M78", 'recommended'] = True  # Leo Triplet
df_combined.loc[df_combined['objectId'] == "M78", 'tags'] = "f/6.3; UHC" 

df_combined.loc[df_combined['objectId'] == "M81", 'recommended'] = True  # The Bode's Galaxy
df_combined.loc[df_combined['objectId'] == "M81", 'tags'] = "f/6.3 - with M82" 

df_combined.loc[df_combined['objectId'] == "M82", 'recommended'] = True  # The Cigar Galaxy
df_combined.loc[df_combined['objectId'] == "M82", 'tags'] = "f/6.3 - with M81" 

df_combined.loc[df_combined['objectId'] == "M94", 'recommended'] = True  # The Cat's Eye Galaxy
df_combined.loc[df_combined['objectId'] == "M94", 'tags'] = "f/10" 

df_combined.loc[df_combined['objectId'] == "M97", 'recommended'] = True  # The Owl Nebula
df_combined.loc[df_combined['objectId'] == "M97", 'tags'] = "f/10; UHC" 

df_combined.loc[df_combined['objectId'] == "M101", 'recommended'] = True  # Pinwheel Galaxy
df_combined.loc[df_combined['objectId'] == "M101", 'tags'] = "f/10" 

df_combined.loc[df_combined['objectId'] == "M104", 'recommended'] = True  # Sombrero Galaxy
df_combined.loc[df_combined['objectId'] == "M104", 'tags'] = "f/10" 

df_combined.loc[df_combined['objectId'] == "C14", 'recommended'] = True  # Double Cluster
df_combined.loc[df_combined['objectId'] == "C14", 'tags'] = "f/10" 

df_combined.loc[df_combined['objectId'] == "C33", 'recommended'] = True  # Eastern Veil
df_combined.loc[df_combined['objectId'] == "C33", 'tags'] = "f/6.3; UHC" 

df_combined.loc[df_combined['objectId'] == "C34", 'recommended'] = True  # Western Veil 
df_combined.loc[df_combined['objectId'] == "C34", 'tags'] = "f/6.3; UHC" 

df_combined.loc[df_combined['objectId'] == "C49", 'recommended'] = True  # Rosette Nebula
df_combined.loc[df_combined['objectId'] == "C49", 'tags'] = "f/6.3; UHC" 

df_combined.loc[df_combined['objectId'] == "C63", 'recommended'] = True  # Helix Nebula
df_combined.loc[df_combined['objectId'] == "C63", 'tags'] = "f/6.3; UHC" 

df_combined.loc[df_combined['objectId'] == "C64", 'recommended'] = True  # Tau CMa
df_combined.loc[df_combined['objectId'] == "C64", 'tags'] = "f/10"

In [9]:
df_combined['objectId'] = df_combined['objectId'].str.lower()
df_combined[0:200]

,friendlyName,objectId,ngcId,ra,dec,type,subType,constellation,magnitude,observationNotes,id,recommended,tags
0,Hoag's Object,hoag,PGC 54559,229.310000,21.585556,galaxy,Ring Galaxy,Serpens,16.000000,NaN,0,True,f/6.3
1,Crab Nebula,m1,NGC 1952,83.625000,22.016667,nebula,Supernova Remnant,Taurus,8.400000,"The Crab Nebula, or M1, is a supernova remnant...",0,True,f/10; UHC
2,M2,m2,NGC 7089,323.375000,-0.816667,cluster,Globular Cluster,Aquarius,6.500000,<NA>,0,False,
3,M3,m3,NGC 5272,205.550000,28.383333,cluster,Globular Cluster,Canes Venatici,6.200000,<NA>,0,False,
4,M4,m4,NGC 6121,245.900000,-26.533333,cluster,Globular Cluster,Scorpius,5.600000,<NA>,0,False,
5,M5,m5,NGC 5904,229.650000,2.083333,cluster,Globular Cluster,Serpens Caput,5.600000,<NA>,0,False,
6,Butterfly Cluster,m6,NGC 6405,265.025000,-32.216667,cluster,Open Cluster,Scorpius,5.300000,"M6, also known as the Butterfly Cluster, is an...",0,True,f/10
7,Ptolemy¹s Cluster,m7,NGC 6475,268.475000,-34.816667,cluster,Open Cluster,Scorpius,4.100000,"M7, known as the Ptolemy Cluster, is a promine...",0,True,f/6.3
8,Lagoon Nebula,m8,NGC 6523,270.950000,-24.383333,nebula,Diffuse Nebula,Sagittarius,6.000000,"The Lagoon Nebula, or M8, is a large and brigh...",0,True,f/6.3; UGC
9,M9,m9,NGC 6333,259.800000,-18.516667,cluster,Globular Cluster,Ophiucus,7.700000,<NA>,0,False,
10,M10,m10,NGC 6254,254.275000,-4.100000,cluster,Globular Cluster,Ophiucus,6.600000,<NA>,0,False,
11,Wild Duck Cluster,m11,NGC 6705,282.775000,-6.266667,cluster,Open Cluster,Scutum,6.300000,"M11, or the Wild Duck Cluster, is an open clus...",0,True,f/10
12,M12,m12,NGC 6218,251.800000,-1.950000,cluster,Globular Cluster,Ophiucus,6.700000,<NA>,0,False,
13,Hercules Globular Cluster,m13,NGC 6205,250.425000,36.466667,cluster,Globular Cluster,Hercules,5.800000,"M13, the Great Globular Cluster in Hercules, i...",0,True,f/10
14,M14,m14,NGC 6402,264.400000,-3.250000,cluster,Globular Cluster,Ophiucus,7.600000,<NA>,0,False,
15,M15,m15,NGC 7078,322.500000,12.166667,cluster,Globular Cluster,Pegasus,6.200000,<NA>,0,False,
16,Eagle Nebula Cluster,m16,NGC 6611,274.700000,-13.783333,cluster,Open Cluster,Serpens Claudia,6.400000,"The Eagle Nebula, or M16, is a young open clus...",0,True,f/6.3; UHC
17,"Omega, Swan, Horseshoe Nebula",m17,NGC 6618,275.200000,-16.183333,nebula,Diffuse Nebula,Sagittarius,7.000000,"M17, also known as the Omega Nebula or the Swa...",0,True,f/6.3; UHC
18,M18,m18,NGC 6613,274.975000,-17.133333,cluster,Open Cluster,Sagittarius,7.500000,<NA>,0,False,
19,M19,m19,NGC 6273,255.650000,-26.266667,cluster,Globular Cluster,Ophiucus,6.800000,<NA>,0,False,
20,Trifid Nebula,m20,NGC 6514,270.575000,-23.033333,nebula,Diffuse Nebula,Sagittarius,9.000000,<NA>,0,False,
21,M21,m21,NGC 6531,271.150000,-22.500000,cluster,Open Cluster,Sagittarius,6.500000,<NA>,0,False,
22,M22,m22,NGC 6656,279.100000,-23.900000,cluster,Globular Cluster,Sagittarius,5.100000,"M22, near the top of the 'teapot' in Sagittari...",0,True,f/10
23,M23,m23,NGC 6494,269.200000,-19.016667,cluster,Open Cluster,Sagittarius,6.900000,<NA>,0,False,
24,Milky Way Patch,m24,NGC 6603,274.600000,-18.416667,star,Star Cloud,Sagittarius,4.600000,<NA>,0,False,
25,IC 4725,m25,<NA>,277.925000,-19.233333,cluster,Open Cluster,Sagittarius,6.500000,<NA>,0,False,
26,M26,m26,NGC 6694,281.300000,-9.400000,cluster,Open Cluster,Scutum,8.000000,<NA>,0,False,
27,Dumbbell Nebula,m27,NGC 6853,299.900000,22.716667,nebula,Planetary Nebula,Vulpecula,7.400000,"M27, known as the Dumbbell Nebula, is a bright...",0,True,f/10; UHC
28,M28,m28,NGC 6626,276.125000,-24.866667,cluster,Globular Cluster,Sagittarius,6.800000,<NA>,0,False,
29,M29,m29,NGC 6913,305.975000,38.533333,cluster,Open Cluster,Cygnus,7.100000,<NA>,0,False,
30,M30,m30,NGC 7099,325.100000,-23.183333,cluster,Globular Cluster,Capricornus,7.200000,<NA>,0,False,
31,Andromeda Galaxy,m31,NGC 224,10.675000,41.266667,galaxy,Spiral Galaxy,Andromeda,3.400000,"The Andromeda Galaxy, known as M31, is one of ...",0,True,f/6.3
32,Satellite of M31,m32,NGC 221,10.675000,40.866667,galaxy,Elliptical Galaxy,Andromeda,8.100000,<NA>,0,False,
33,Triangulum/Pinwheel Galaxy,m33,NGC 598,23.475000,30.650000,galaxy,Spiral Galaxy,Triangulum,5.700000,<NA>,0,True,f/6.3
34,M34,m34,NGC 1039,40.500000,42.783333,cluster,Open Cluster,Perseus,5.500000,<NA>,0,False,
35,M35,m35,NGC 2168,92.225000,24.333333,cluster,Open Cluster,Gemini,5.300000,<NA>,0,False,
36,M36,m36,NGC 1960,84.025000,34.133333,cluster,Open Cluster,Auriga,6.300000,<NA>,0,False,
37,M37,m37,NGC 2099,88.100000,32.550000,cluster,Open Cluster,Auriga,6.200000,<NA>,0,False,
38,M38,m38,NGC 1912,82.175000,35.833333,cluster,Open Cluster,Auriga,7.400000,<NA>,0,False,
39,M39,m39,NGC 7092,323.050000,48.433333,cluster,Open Cluster,Cygnus,5.200000,<NA>,0,False,
40,Winecke 4,m40,<NA>,185.550000,58.083333,star,Double Star,Ursa Major,<NA>,<NA>,0,False,
41,M41,m41,NGC 2287,101.750000,-20.733333,cluster,Open Cluster,Canis Major,4.600000,<NA>,0,False,
42,Great Orion Nebula,m42,NGC 1976,83.850000,-5.450000,nebula,Diffuse Nebula,Orion,4.000000,"The Orion Nebula, or M42, is a diffuse nebula ...",0,True,f/6.3; UHC
43,de Mairan¹s Nebula,m43,NGC 1982,83.900000,-5.266667,nebula,Diffuse Nebula,Orion,9.000000,<NA>,0,True,f/6.3; UHC
44,Beehive Cluster (Praesepe),m44,NGC 2632,130.025000,19.983333,cluster,Open Cluster,Cancer,3.700000,<NA>,0,True,f/6.3; UHC
45,"Pleiades, Subaru, Seven Sisters",m45,<NA>,56.750000,24.120000,cluster,Open Cluster,Taurus,1.600000,"M45, commonly known as the Pleiades or the Sev...",0,True,f/6.3
46,M46,m46,NGC 2437,115.450000,-14.816667,cluster,Open Cluster,Puppis,6.000000,<NA>,0,False,
47,M47,m47,NGC 2422,114.150000,-14.500000,cluster,Open Cluster,Puppis,5.200000,<NA>,0,False,
48,M48,m48,NGC 2548,123.450000,-5.800000,cluster,Open Cluster,Hydra,5.500000,<NA>,0,False,
49,M49,m49,NGC 4472,187.450000,8.000000,galaxy,Elliptical Galaxy,Virgo,8.400000,<NA>,0,False,
50,M50,m50,NGC 2323,105.800000,-8.333333,cluster,Open Cluster,Monocerus,6.300000,<NA>,0,False,
51,Whirlpool Galaxy,m51,NGC 5194,202.475000,47.200000,galaxy,Spiral Galaxy,Canes Venatici,8.400000,"M51, also known as the Whirlpool Galaxy, is a ...",0,True,f/10
52,M52,m52,NGC 7654,351.050000,61.583333,cluster,Open Cluster,Cassiopeia,7.300000,<NA>,0,False,
53,M53,m53,NGC 5024,198.225000,18.166667,cluster,Globular Cluster,Coma Berenices,7.600000,<NA>,0,False,
54,M54,m54,NGC 6715,283.775000,-30.483333,cluster,Globular Cluster,Sagittarius,7.600000,<NA>,0,False,
55,M55,m55,NGC 6809,295.000000,-30.966667,cluster,Globular Cluster,Sagittarius,6.300000,<NA>,0,False,
56,M56,m56,NGC 6779,289.150000,30.183333,cluster,Globular Cluster,Lyra,8.300000,<NA>,0,False,
57,Ring Nebula,m57,NGC 6720,283.400000,33.033333,nebula,Planetary Nebula,Lyra,8.800000,"M57, the Ring Nebula, is a planetary nebula in...",0,True,f/10
58,M58,m58,NGC 4579,189.425000,11.816667,galaxy,Spiral Galaxy,Virgo,9.700000,<NA>,0,False,
59,M59,m59,NGC 4621,190.500000,11.650000,galaxy,Elliptical Galaxy,Virgo,9.600000,<NA>,0,False,
60,M60,m60,NGC 4649,190.925000,11.550000,galaxy,Elliptical Galaxy,Virgo,8.800000,<NA>,0,False,
61,M61,m61,NGC 4303,185.475000,4.466667,galaxy,Spiral Galaxy,Virgo,9.700000,<NA>,0,False,
62,M62,m62,NGC 6266,255.300000,-30.116667,cluster,Globular Cluster,Ophiucus,6.500000,<NA>,0,False,
63,Sunflower Galaxy,m63,NGC 5055,198.950000,42.033333,galaxy,Spiral Galaxy,Canes Venatici,8.600000,<NA>,0,True,f/10
64,Blackeye Galaxy,m64,NGC 4826,194.175000,21.683333,galaxy,Spiral Galaxy,Coma Berenices,8.500000,<NA>,0,True,f/10
65,M65,m65,NGC 3623,169.725000,13.083333,galaxy,Spiral Galaxy,Leo,9.300000,<NA>,0,True,f/6.3 - Leo Triplet
66,M66,m66,NGC 3627,170.050000,12.983333,galaxy,Spiral Galaxy,Leo,8.900000,<NA>,0,True,f/6.3 - Leo Triplet
67,M67,m67,NGC 2682,132.600000,11.816667,cluster,Open Cluster,Cancer,6.100000,<NA>,0,False,
68,M68,m68,NGC 4590,189.875000,-26.750000,cluster,Globular Cluster,Hydra,7.800000,<NA>,0,False,
69,M69,m69,NGC 6637,277.850000,-32.350000,cluster,Globular Cluster,Sagittarius,7.600000,<NA>,0,False,
70,M70,m70,NGC 6681,280.800000,-32.300000,cluster,Globular Cluster,Sagittarius,7.900000,<NA>,0,False,
71,M71,m71,NGC 6838,298.450000,18.783333,cluster,Globular Cluster,Sagitta,8.300000,<NA>,0,False,
72,M72,m72,NGC 6981,313.375000,-12.533333,cluster,Globular Cluster,Aquarius,9.300000,<NA>,0,False,
73,Group of 4 stars,m73,NGC 6994,314.750000,-12.633333,star,Group/Asterism,Aquarius,9.000000,<NA>,0,False,
74,M74,m74,NGC 628,24.175000,15.783333,galaxy,Spiral Galaxy,Pisces,9.400000,<NA>,0,False,
75,M75,m75,NGC 6864,301.525000,-21.916667,cluster,Globular Cluster,Sagittarius,8.500000,<NA>,0,False,
76,"Little Dumbell, Cork, Butterfly Nebula",m76,NGC 650,25.575000,51.566667,nebula,Planetary Nebula,Perseus,10.100000,<NA>,0,False,
77,Cetus A,m77,NGC 1068,40.675000,0.016667,galaxy,Spiral Galaxy,Cetus,8.900000,<NA>,0,False,
78,M78,m78,NGC 2068,86.675000,0.050000,nebula,Diffuse Nebula,Orion,8.300000,<NA>,0,True,f/6.3; UHC
79,M79,m79,NGC 1904,81.125000,-24.550000,cluster,Globular Cluster,Lepus,7.700000,<NA>,0,False,
80,M80,m80,NGC 6093,244.250000,-22.983333,cluster,Globular Cluster,Scorpius,7.300000,<NA>,0,False,
81,Bode¹s Galaxy,m81,NGC 3031,148.900000,69.066667,galaxy,Spiral Galaxy,Ursa Major,6.900000,"M81, or Bode's Galaxy, is a grand design spira...",0,True,f/6.3 - with M82
82,Cigar Galaxy,m82,NGC 3034,148.950000,69.683333,galaxy,Irregular Galaxy,Ursa Major,8.400000,"M82, the Cigar Galaxy, is a starburst galaxy n...",0,True,f/6.3 - with M81
83,Southern Pinwheel Galaxy,m83,NGC 5236,204.250000,-29.866667,galaxy,Spiral Galaxy,Hydra,7.600000,<NA>,0,False,
84,M84,m84,NGC 4374,186.275000,12.883333,galaxy,Lenticular (S0) Galaxy,Virgo,9.100000,<NA>,0,False,
85,M85,m85,NGC 4382,186.350000,18.183333,galaxy,Lenticular (S0) Galaxy,Coma Berenices,9.100000,<NA>,0,False,
86,FAUST V051,m86,NGC 4406,186.550000,12.950000,galaxy,Lenticular (S0) Galaxy,Virgo,8.900000,<NA>,0,False,
87,Virgo A,m87,NGC 4486,187.700000,12.400000,galaxy,Elliptical Galaxy,Virgo,8.600000,<NA>,0,False,
88,M88,m88,NGC 4501,188.000000,14.416667,galaxy,Spiral Galaxy,Coma Berenices,9.600000,<NA>,0,False,
89,M89,m89,NGC 4552,188.925000,12.550000,galaxy,Elliptical Galaxy,Virgo,9.800000,<NA>,0,False,
90,M90,m90,NGC 4569,189.200000,13.166667,galaxy,Spiral Galaxy,Virgo,9.500000,<NA>,0,False,
91,M91,m91,NGC 4548,188.850000,14.500000,galaxy,Spiral Galaxy,Coma Berenices,10.200000,<NA>,0,False,
92,M92,m92,NGC 6341,259.275000,43.133333,cluster,Globular Cluster,Hercules,6.400000,<NA>,0,False,
93,M93,m93,NGC 2447,116.150000,-23.866667,cluster,Open Cluster,Puppis,6.000000,<NA>,0,False,
94,M94,m94,NGC 4736,192.725000,41.116667,galaxy,Spiral Galaxy,Canes Venatici,8.200000,<NA>,0,True,f/10
95,M95,m95,NGC 3351,161.000000,11.700000,galaxy,Spiral Galaxy,Leo,9.700000,<NA>,0,False,
96,M96,m96,NGC 3368,161.700000,11.816667,galaxy,Spiral Galaxy,Leo,9.200000,<NA>,0,False,
97,Owl Nebula,m97,NGC 3587,168.700000,55.016667,nebula,Planetary Nebula,Ursa Major,9.900000,<NA>,0,True,f/10; UHC
98,M98,m98,NGC 4192,183.450000,14.900000,galaxy,Spiral Galaxy,Coma Berenices,10.100000,<NA>,0,False,
99,Virgo Cluster Pinwheel,m99,NGC 4254,184.700000,14.416667,galaxy,Spiral Galaxy,Coma Berenices,9.900000,<NA>,0,False,
100,M100,m100,NGC 4321,185.725000,15.816667,galaxy,Spiral Galaxy,Coma Berenices,9.300000,<NA>,0,False,
101,Pinwheel Galaxy,m101,NGC 5457,210.800000,54.350000,galaxy,Spiral Galaxy,Ursa Major,7.900000,<NA>,0,True,f/10
102,Spindle Galaxy,m102,NGC 5866,226.625000,55.766667,galaxy,Lenticular (S0) Galaxy,Draco,9.900000,<NA>,0,False,
103,M103,m103,NGC 581,23.300000,60.700000,cluster,Open Cluster,Cassiopeia,7.400000,<NA>,0,False,
104,Sombrero Galaxy,m104,NGC 4594,190.000000,-11.616667,galaxy,Spiral Galaxy,Virgo,8.000000,<NA>,0,True,f/10
105,M105,m105,NGC 3379,161.950000,12.583333,galaxy,Elliptical Galaxy,Leo,9.300000,<NA>,0,False,
106,M106,m106,NGC 4258,184.750000,47.300000,galaxy,Spiral Galaxy,Canes Venatici,8.400000,<NA>,0,False,
107,M107,m107,NGC 6171,248.125000,-13.050000,cluster,Globular Cluster,Ophiucus,7.900000,<NA>,0,False,
108,M108,m108,NGC 3556,167.875000,55.666667,galaxy,Spiral Galaxy,Ursa Major,10.000000,<NA>,0,False,
109,M109,m109,NGC 3992,179.400000,53.383333,galaxy,Spiral Galaxy,Ursa Major,9.800000,<NA>,0,False,
110,Satellite of M31,m110,NGC 205,10.100000,41.683333,galaxy,Elliptical Galaxy,Andromeda,8.500000,<NA>,0,False,
111,NGC 188,c1,NGC 188,11.100000,85.333333,cluster,Open Cluster,Cepheus,8.100000,caldwell 1 data,0,False,
112,Bow-Tie Nebula,c2,NGC 40,3.250000,72.533333,nebula,Planetary Nebula,Cepheus,12.400000,<NA>,0,False,
113,NGC 4236,c3,NGC 4236,184.175000,69.466667,galaxy,Spiral Galaxy,Draco,9.700000,<NA>,0,False,
114,IRIS Nebula,c4,NGC 7023,315.450000,68.200000,nebula,Bright Nebula,Cepheus,<NA>,<NA>,0,False,
115,Hidden Galaxy,c5,<NA>,56.700000,68.100000,galaxy,Spiral Galaxy,Camelopardalis,9.200000,<NA>,0,False,
116,Cat's Eye Nebula,c6,NGC 6543,269.650000,66.633333,nebula,Planetary Nebula,Draco,8.100000,<NA>,0,False,
117,NGC 2403,c7,NGC 2403,114.225000,65.600000,galaxy,Spiral Galaxy,Camelopardalis,8.400000,<NA>,0,False,
118,NGC 559,c8,NGC 559,22.375000,63.300000,cluster,Open Cluster,Cassiopeia,9.500000,<NA>,0,False,
119,Cave Nebula,c9,<NA>,344.200000,62.616667,nebula,Bright Nebula,Cepheus,<NA>,<NA>,0,False,
120,NGC 663,c10,NGC 663,26.500000,61.250000,cluster,Open Cluster,Cassiopeia,7.100000,<NA>,0,False,
121,Bubble Nebula,c11,NGC 7635,350.175000,61.200000,nebula,Bright Nebula,Cassiopeia,<NA>,<NA>,0,False,
122,Fireworks Galaxy,c12,NGC 6946,308.700000,60.150000,galaxy,Spiral Galaxy,Cepheus,8.900000,<NA>,0,False,
123,Owl Cluster,c13,NGC 457,19.775000,58.333333,cluster,Open Cluster,Cassiopeia,6.400000,<NA>,0,False,
124,Double Cluster (h&X Persei),c14,NGC 869,35.000000,57.133333,cluster,Open Cluster,Perseus,4.300000,"Caldwell 14, also known as the Double Cluster,...",0,True,f/10
125,Blinking Planetary,c15,NGC 6826,296.200000,50.516667,nebula,Planetary Nebula,Cygnus,8.800000,<NA>,0,False,
126,NGC 7243,c16,NGC 7243,333.825000,49.883333,cluster,Open Cluster,Lacerta,6.400000,<NA>,0,False,
127,NGC 147,c17,NGC 147,8.300000,48.500000,galaxy,Elliptical Galaxy,Cassiopeia,9.300000,<NA>,0,False,
128,NGC 185,c18,NGC 185,9.750000,48.333333,galaxy,Elliptical Galaxy,Cassiopeia,9.200000,<NA>,0,False,
129,Cocoon Nebula,c19,<NA>,328.375000,47.266667,nebula,Bright Nebula,Cygnus,<NA>,<NA>,0,False,
130,North America Nebula,c20,NGC 7000,314.700000,44.333333,nebula,Bright Nebula,Cygnus,<NA>,<NA>,0,False,
131,NGC 4449,c21,NGC 4449,187.050000,44.100000,galaxy,Irregular Galaxy,Canes Venatici,9.400000,<NA>,0,False,
132,Copeland's Blue Snowball,c22,NGC 7662,351.475000,42.550000,nebula,Planetary Nebula,Andromeda,8.300000,<NA>,0,False,
133,Silver Sliver Galaxy,c23,NGC 891,35.650000,42.350000,galaxy,Spiral Galaxy,Andromeda,9.900000,<NA>,0,False,
134,Perseus A,c24,NGC 1275,49.950000,41.516667,galaxy,Irregular Galaxy,Perseus,11.600000,<NA>,0,False,
135,NGC 2419,c25,NGC 2419,114.525000,38.883333,cluster,Globular Cluster,Lynx,10.400000,<NA>,0,False,
136,NGC 4244,c26,NGC 4244,184.375000,37.816667,galaxy,Spiral Galaxy,Canes Venatici,10.200000,<NA>,0,False,
137,Crescent Nebula,c27,NGC 6888,303.000000,38.350000,nebula,Bright Nebula,Cygnus,<NA>,<NA>,0,False,
138,NGC 752,c28,NGC 752,29.450000,37.683333,cluster,Open Cluster,Andromeda,5.700000,<NA>,0,False,
139,NGC 5005,c29,NGC 5005,197.725000,37.050000,galaxy,Spiral Galaxy,Canes Venatici,9.800000,<NA>,0,False,
140,NGC 7331,c30,NGC 7331,339.275000,34.416667,galaxy,Spiral Galaxy,Pegasus,9.500000,<NA>,0,False,
141,Flaming Star Nebula,c31,<NA>,79.050000,34.266667,nebula,Bright Nebula,Auriga,<NA>,<NA>,0,False,
142,Whale Galaxy,c32,NGC 4631,190.525000,32.533333,galaxy,Spiral Galaxy,Canes Venatici,9.300000,<NA>,0,False,
143,East Veil,c33,NGC 6992,314.100000,31.716667,nebula,Supernova Remnant,Cygnus,<NA>,"Caldwell 33, located in Draco, is a spiral gal...",0,True,f/6.3; UHC
144,West Veil,c34,NGC 6960,311.425000,30.716667,nebula,Supernova Remnant,Cygnus,<NA>,"Caldwell 34, part of the Veil Nebula, is a sup...",0,True,f/6.3; UHC
145,Coma B,c35,NGC 4889,195.025000,27.983333,galaxy,Elliptical Galaxy,Coma Berenices,11.400000,<NA>,0,False,
146,NGC 4559,c36,NGC 4559,189.000000,27.966667,galaxy,Spiral Galaxy,Coma Berenices,9.800000,<NA>,0,False,
147,NGC 6885,c37,NGC 6885,303.000000,26.483333,cluster,Open Cluster,Vulpecula,5.900000,<NA>,0,False,
148,Needle Galaxy,c38,NGC 4565,189.075000,25.983333,galaxy,Spiral Galaxy,Coma Berenices,9.600000,<NA>,0,False,
149,Eskimo/Clown Face Nebula,c39,NGC 2392,112.300000,20.916667,nebula,Planetary Nebula,Gemini,9.200000,<NA>,0,False,
150,NGC 3626,c40,NGC 3626,170.025000,18.350000,galaxy,Spiral Galaxy,Leo,10.900000,<NA>,0,False,
151,Hyades Cluster,c41,<NA>,66.750000,16.000000,cluster,Open Cluster,Taurus,0.500000,<NA>,0,False,
152,NGC 7006,c42,NGC 7006,315.375000,16.183333,cluster,Globular Cluster,Delphinus,10.600000,<NA>,0,False,
153,NGC 7814,c43,NGC 7814,0.825000,16.150000,galaxy,Spiral Galaxy,Pegasus,10.500000,<NA>,0,False,
154,NGC 7479,c44,NGC 7479,346.225000,12.316667,galaxy,Spiral Galaxy,Pegasus,11.000000,<NA>,0,False,
155,NGC 5248,c45,NGC 5248,204.375000,8.883333,galaxy,Spiral Galaxy,Bootes,10.200000,<NA>,0,False,
156,Hubble's Variable Nebula,c46,NGC 2261,99.800000,8.733333,nebula,Bright Nebula,Monoceros,<NA>,<NA>,0,False,
157,NGC 6934,c47,NGC 6934,308.550000,7.400000,cluster,Globular Cluster,Delphinus,8.900000,<NA>,0,False,
158,NGC 2775,c48,NGC 2775,137.575000,7.033333,galaxy,Spiral Galaxy,Canes Major,10.300000,<NA>,0,False,
159,Rosette Nebula,c49,NGC 2237,98.075000,5.050000,nebula,Bright Nebula,Monoceros,<NA>,"Caldwell 49, known as the Rosette Nebula, is a...",0,True,f/6.3; UHC
160,Satellite Cluster,c50,NGC 2244,98.100000,4.866667,cluster,Open Cluster,Monoceros,4.800000,<NA>,0,False,
161,IC 1613,c51,<NA>,16.200000,2.116667,galaxy,Irregular Galaxy,Cetus,9.300000,<NA>,0,False,
162,NGC 4697,c52,NGC 4697,192.150000,-5.800000,galaxy,Elliptical Galaxy,Virgo,9.300000,<NA>,0,False,
163,Spindle Galaxy,c53,NGC 3115,151.300000,-7.716667,galaxy,Elliptical Galaxy,Sextans,9.100000,<NA>,0,False,
164,NGC 2506,c54,NGC 2506,120.050000,-10.783333,cluster,Open Cluster,Monoceros,7.600000,<NA>,0,False,
165,Saturn Nebula,c55,NGC 7009,316.050000,-11.366667,nebula,Planetary Nebula,Aquarius,8.000000,<NA>,0,False,
166,Skull Nebula,c56,NGC 246,11.750000,-11.883333,nebula,Planetary Nebula,Cetus,10.900000,<NA>,0,False,
167,Barnard's Galaxy,c57,NGC 6822,296.225000,-14.800000,galaxy,Irregular Galaxy,Sagittarius,8.800000,<NA>,0,False,
168,Caroline's Cluster,c58,NGC 2360,109.450000,-15.616667,cluster,Open Cluster,Canis Major,7.200000,<NA>,0,False,
169,Jupiter's Ghost Nebula,c59,NGC 3242,156.200000,-18.633333,nebula,Planetary Nebula,Hydra,7.800000,<NA>,0,False,
170,Antennae Galaxies,c60,NGC 4038,180.475000,-18.866667,galaxy,Spiral Galaxy,Corvus,10.700000,<NA>,0,False,
171,Antennae Galaxies,c61,NGC 4039,180.475000,-18.883333,galaxy,Spiral Galaxy,Corvus,10.700000,<NA>,0,False,
172,NGC 247,c62,NGC 247,11.775000,-20.766667,galaxy,Spiral Galaxy,Cetus,9.100000,<NA>,0,False,
173,Helix Nebula,c63,NGC 7293,337.400000,-20.800000,nebula,Planetary Nebula,Aquarius,7.300000,<NA>,0,True,f/6.3; UHC
174,Tau CMa,c64,NGC 2362,109.700000,-24.950000,cluster,Open Cluster,Canis Major,4.100000,"Caldwell 64, the Black Eye Galaxy or M64, is a...",0,True,f/10
175,Sculptor Filament,c65,NGC 253,11.900000,-25.283333,galaxy,Spiral Galaxy,Sculptor,7.100000,<NA>,0,False,
176,NGC 5694,c66,NGC 5694,219.900000,-26.533333,cluster,Globular Cluster,Hydra,10.200000,<NA>,0,False,
177,NGC 1097,c67,NGC 1097,41.575000,-30.283333,galaxy,Spiral Galaxy,Fornax,9.200000,<NA>,0,False,
178,R CrA Nebula,c68,NGC 6729,285.475000,-36.950000,nebula,Bright Nebula,Corona Australis,<NA>,<NA>,0,False,
179,Bug Nebula,c69,NGC 6302,258.425000,-37.100000,nebula,Planetary Nebula,Scorpius,9.600000,<NA>,0,False,
180,NGC 300,c70,NGC 300,13.725000,-37.683333,galaxy,Spiral Galaxy,Sculptor,8.700000,<NA>,0,False,
181,NGC 2477,c71,NGC 2477,118.075000,-38.550000,cluster,Open Cluster,Puppis,5.800000,<NA>,0,False,

In [10]:
df_combined.to_json('items.json', orient='records', lines=False)